// Holds only the newest CSV batch to import — replace the contents of NEW_STOCK_ITEMS
// (and NEW_LOCATIONS, if the batch introduces bin codes not already in the DB) each time
// a new stock sheet comes in, then run `npm run import-stock`.
// Current batch: STOCK 13.08.26.csv (160 items).
export const NEW_STOCK_ITEMS = [
  {
    "tally": null,
    "material": "BENZOIN KHODI SOLID",
    "brand": "GOLDEN",
    "packing": 50,
    "article": null,
    "packingDetail": "2×50kg",
    "totalStock": 100,
    "batchNo": "P062613",
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 100,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BENZOIN KHODI SOLID",
    "brand": "GOLDEN",
    "packing": 25,
    "article": null,
    "packingDetail": "5×25kg",
    "totalStock": 125,
    "batchNo": "P062613",
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 125,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BASE PATCHOULI RD # 1629",
    "brand": "GLOBAL",
    "packing": null,
    "article": null,
    "packingDetail": "9.8kg loose",
    "totalStock": 9.8,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 9.8,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PATCHOULI OIL 30+",
    "brand": "NATURA",
    "packing": null,
    "article": null,
    "packingDetail": "0.55kg loose",
    "totalStock": 0.55,
    "batchNo": "251101486",
    "mfg": "2025-07-26",
    "exp": "2027-07-25",
    "in": 0,
    "out": 0,
    "opening": 0.55,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PATCHOULI OIL STD",
    "brand": "SB",
    "packing": null,
    "article": null,
    "packingDetail": "2.5kg loose",
    "totalStock": 2.5,
    "batchNo": "244543",
    "mfg": "2024-06-05",
    "exp": "2026-06-05",
    "in": 0,
    "out": 0,
    "opening": 2.5,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PATCHOULI OIL GREEN",
    "brand": "SBA",
    "packing": 25,
    "article": null,
    "packingDetail": "1×25kg",
    "totalStock": 25,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 25,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PATCHOULI OIL GREEN",
    "brand": "SBA",
    "packing": null,
    "article": null,
    "packingDetail": "20.5kg loose",
    "totalStock": 20.5,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 20.5,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PATCHOULI DARK 30+",
    "brand": "VAN AROMA",
    "packing": null,
    "article": null,
    "packingDetail": "4.4kg loose",
    "totalStock": 4.4,
    "batchNo": "26010001-1",
    "mfg": "2026-01-04",
    "exp": "2029-01-05",
    "in": 0,
    "out": 0,
    "opening": 4.4,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ACETANTSOL",
    "brand": "CHINA (COLOUR CHANGE)",
    "packing": null,
    "article": null,
    "packingDetail": "0.8kg loose",
    "totalStock": 0.8,
    "batchNo": "250208",
    "mfg": "2025-02-01",
    "exp": "2026-01-01",
    "in": 0,
    "out": 0,
    "opening": 0.8,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GURJAN OIL DARK",
    "brand": "NATURA",
    "packing": null,
    "article": null,
    "packingDetail": "1.5kg loose",
    "totalStock": 1.5,
    "batchNo": "241100731",
    "mfg": "2024-04-04",
    "exp": "2026-04-03",
    "in": 0,
    "out": 0,
    "opening": 1.5,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GURJUN BALSUM DARK",
    "brand": "KK",
    "packing": null,
    "article": null,
    "packingDetail": "21.1kg loose",
    "totalStock": 21.1,
    "batchNo": "251812",
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 21.1,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "LABDANUM ABS",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "11kg loose",
    "totalStock": 11,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 11,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "LABDANUM ABS",
    "brand": "OPUS",
    "packing": null,
    "article": null,
    "packingDetail": "9.8kg loose",
    "totalStock": 9.8,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 9.8,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "HEXYL SALICYLATE",
    "brand": "UK",
    "packing": null,
    "article": null,
    "packingDetail": "2.8kg loose",
    "totalStock": 2.8,
    "batchNo": "007942",
    "mfg": "2024-09-13",
    "exp": "2025-09-12",
    "in": 0,
    "out": 0,
    "opening": 2.8,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "HEXYL SALICYLATE",
    "brand": "UK",
    "packing": null,
    "article": null,
    "packingDetail": "9.5kg loose",
    "totalStock": 9.5,
    "batchNo": "007517",
    "mfg": "2023-10-13",
    "exp": "2024-10-12",
    "in": 0,
    "out": 0,
    "opening": 9.5,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "HEXYL SALICYLATE",
    "brand": "UK",
    "packing": null,
    "article": null,
    "packingDetail": "25kg loose",
    "totalStock": 25,
    "batchNo": "UK-HS-2803",
    "mfg": "2026-03-28",
    "exp": "2027-03-27",
    "in": 0,
    "out": 0,
    "opening": 25,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "HEXYL SALICYLATE",
    "brand": "UK",
    "packing": 35,
    "article": null,
    "packingDetail": "1×35kg",
    "totalStock": 35,
    "batchNo": "UK-HS-2803",
    "mfg": "2026-03-28",
    "exp": "2027-03-27",
    "in": 0,
    "out": 0,
    "opening": 35,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "HEXYL SALICYLATE",
    "brand": "BVC",
    "packing": 30,
    "article": null,
    "packingDetail": "1×30kg",
    "totalStock": 30,
    "batchNo": "D059670974",
    "mfg": "2026-07-03",
    "exp": "2028-07-03",
    "in": 0,
    "out": 0,
    "opening": 30,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "HEXYL SALICYLATE",
    "brand": "BVC",
    "packing": null,
    "article": null,
    "packingDetail": "14.8kg loose",
    "totalStock": 14.8,
    "batchNo": "D059670974",
    "mfg": "2026-07-03",
    "exp": "2028-07-03",
    "in": 0,
    "out": 0,
    "opening": 14.8,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "HEXYL SALICYLATE",
    "brand": "BVC",
    "packing": null,
    "article": null,
    "packingDetail": "2.5kg loose",
    "totalStock": 2.5,
    "batchNo": "C054--3620",
    "mfg": "2025-05-15",
    "exp": "2027-05-15",
    "in": 0,
    "out": 0,
    "opening": 2.5,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "HEXYL SALICYLATE",
    "brand": "BVC",
    "packing": null,
    "article": null,
    "packingDetail": "0.4kg loose",
    "totalStock": 0.4,
    "batchNo": "C059632822",
    "mfg": "2025-05-03",
    "exp": "2027-05-03",
    "in": 0,
    "out": 0,
    "opening": 0.4,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "HEXYL SALICYLATE",
    "brand": "BVC",
    "packing": null,
    "article": null,
    "packingDetail": "0.74kg loose",
    "totalStock": 0.74,
    "batchNo": "C059646960",
    "mfg": "2025-10-14",
    "exp": "2027-10-14",
    "in": 0,
    "out": 0,
    "opening": 0.74,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ALLYL HEPTOATE",
    "brand": "ORIENTAL (OLD MIX)",
    "packing": null,
    "article": null,
    "packingDetail": "6.7kg loose",
    "totalStock": 6.7,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 6.7,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ALLYL HEPTOATE",
    "brand": "ORIENTAL",
    "packing": null,
    "article": null,
    "packingDetail": "2.65kg loose",
    "totalStock": 2.65,
    "batchNo": "LN060231",
    "mfg": "2026-05-19",
    "exp": "2027-05-19",
    "in": 0,
    "out": 0,
    "opening": 2.65,
    "location": "F1A21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CITRONELLYL NITRILE",
    "brand": "PRIVI (OLD)",
    "packing": null,
    "article": null,
    "packingDetail": "4.95kg loose",
    "totalStock": 4.95,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 4.95,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CITRONELLYL NITRILE",
    "brand": "PRIVI",
    "packing": 25,
    "article": null,
    "packingDetail": "2×25kg",
    "totalStock": 50,
    "batchNo": "0000407221",
    "mfg": "2025-10-12",
    "exp": "2027-10-02",
    "in": 0,
    "out": 0,
    "opening": 50,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "IONONE 100%",
    "brand": "JAYSHREE",
    "packing": null,
    "article": null,
    "packingDetail": "5kg loose",
    "totalStock": 5,
    "batchNo": "2025080101R-002",
    "mfg": "2025-08-01",
    "exp": "2026-07-31",
    "in": 0,
    "out": 0,
    "opening": 5,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "IONONE 100%",
    "brand": "PRIVI",
    "packing": null,
    "article": null,
    "packingDetail": "8.5kg loose",
    "totalStock": 8.5,
    "batchNo": "LN060176",
    "mfg": "2026-04-20",
    "exp": "2027-04-19",
    "in": 0,
    "out": 0,
    "opening": 8.5,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "SANDALUM",
    "brand": "KALSUTRA",
    "packing": null,
    "article": null,
    "packingDetail": "13.3kg loose",
    "totalStock": 13.3,
    "batchNo": "SND-250601",
    "mfg": "2025-06-01",
    "exp": "2027-06-01",
    "in": 0,
    "out": 0,
    "opening": 13.3,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "SANDALUM",
    "brand": "KALSUTRA",
    "packing": 25,
    "article": null,
    "packingDetail": "1×25kg",
    "totalStock": 25,
    "batchNo": "SND-251101",
    "mfg": "2025-11-01",
    "exp": "2027-11-01",
    "in": 0,
    "out": 0,
    "opening": 25,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "VERDYL ACETATE",
    "brand": "KLP",
    "packing": null,
    "article": null,
    "packingDetail": "0.9kg loose",
    "totalStock": 0.9,
    "batchNo": "2503026",
    "mfg": "2025-03-12",
    "exp": "2027-03-11",
    "in": 0,
    "out": 0,
    "opening": 0.9,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CITRONELLYL NITRILE",
    "brand": "PRIVI",
    "packing": null,
    "article": null,
    "packingDetail": "17.4kg loose",
    "totalStock": 17.4,
    "batchNo": "0000407221",
    "mfg": "2025-02-12",
    "exp": "2027-10-02",
    "in": 0,
    "out": 0,
    "opening": 17.4,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BICYCLONONAL ACETONE",
    "brand": "FINE FRAGRANCE",
    "packing": null,
    "article": null,
    "packingDetail": "10.9kg loose",
    "totalStock": 10.9,
    "batchNo": "0017021241",
    "mfg": "2024-10-29",
    "exp": "2027-10-29",
    "in": 0,
    "out": 0,
    "opening": 10.9,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ERDYL PROPIONAT",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "3.3kg loose",
    "totalStock": 3.3,
    "batchNo": "VAN/2409043",
    "mfg": "2024-09-06",
    "exp": "2026-09-05",
    "in": 0,
    "out": 0,
    "opening": 3.3,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "VETIVERT STD",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "4.95kg loose",
    "totalStock": 4.95,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 4.95,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "VETIVER STD",
    "brand": "HEMANI",
    "packing": null,
    "article": null,
    "packingDetail": "2.5kg loose",
    "totalStock": 2.5,
    "batchNo": "CO5360",
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 2.5,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NEROL",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "2.6kg loose",
    "totalStock": 2.6,
    "batchNo": "01105029U0",
    "mfg": "2025-03-12",
    "exp": "2027-03-12",
    "in": 0,
    "out": 0,
    "opening": 2.6,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NATURAL ?-SINENSAL 20",
    "brand": "ISOBIONICS",
    "packing": 1,
    "article": null,
    "packingDetail": "4×1kg",
    "totalStock": 4,
    "batchNo": "0029985008",
    "mfg": "2025-12-17",
    "exp": "2027-01-05",
    "in": 0,
    "out": 0,
    "opening": 4,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NATURAL VALENCENE 75",
    "brand": "ISOBIONICS",
    "packing": 1,
    "article": null,
    "packingDetail": "3×1kg",
    "totalStock": 3,
    "batchNo": "0029346766",
    "mfg": "2025-04-24",
    "exp": "2028-04-23",
    "in": 0,
    "out": 0,
    "opening": 3,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NATURAL VALENCENE 75",
    "brand": "ISOBIONICS",
    "packing": null,
    "article": null,
    "packingDetail": "0.5kg loose",
    "totalStock": 0.5,
    "batchNo": "0029346766",
    "mfg": "2025-04-24",
    "exp": "2028-04-23",
    "in": 0,
    "out": 0,
    "opening": 0.5,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NATURAL VALENCENE 75",
    "brand": "ISOBIONICS",
    "packing": null,
    "article": null,
    "packingDetail": "0.15kg loose",
    "totalStock": 0.15,
    "batchNo": "0029346766",
    "mfg": "2025-04-24",
    "exp": "2028-04-23",
    "in": 0,
    "out": 0,
    "opening": 0.15,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NATURAL VALENCENE 75",
    "brand": "ISOBIONICS",
    "packing": 1,
    "article": null,
    "packingDetail": "3×1kg",
    "totalStock": 3,
    "batchNo": "0029302082",
    "mfg": "2025-04-04",
    "exp": "2028-04-03",
    "in": 0,
    "out": 0,
    "opening": 3,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NATURAL CADINENE 95",
    "brand": "BASF",
    "packing": 1,
    "article": null,
    "packingDetail": "8×1kg",
    "totalStock": 8,
    "batchNo": "24ID07DC95",
    "mfg": "2024-12-12",
    "exp": "2027-12-13",
    "in": 0,
    "out": 0,
    "opening": 8,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NATURAL CADINENE 95",
    "brand": "BASF",
    "packing": 0.5,
    "article": null,
    "packingDetail": "1×0.5kg",
    "totalStock": 0.5,
    "batchNo": "24ID07DC95",
    "mfg": "2024-12-12",
    "exp": "2027-12-13",
    "in": 0,
    "out": 0,
    "opening": 0.5,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NATURAL CADINENE 95",
    "brand": "BASF",
    "packing": 1,
    "article": null,
    "packingDetail": "1×1kg",
    "totalStock": 1,
    "batchNo": "24ID07DC95",
    "mfg": "2024-12-13",
    "exp": "2027-12-13",
    "in": 0,
    "out": 0,
    "opening": 1,
    "location": "F1A22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ARQUAD 2 HT- 75",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "19.6kg loose",
    "totalStock": 19.6,
    "batchNo": "B25040981",
    "mfg": "2025-04-09",
    "exp": "2027-04-09",
    "in": 0,
    "out": 0,
    "opening": 19.6,
    "location": "F1A23",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ARQUAD 2 HT- 75",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "25.9kg loose",
    "totalStock": 25.9,
    "batchNo": "B25040981",
    "mfg": "2025-04-09",
    "exp": "2027-04-09",
    "in": 0,
    "out": 0,
    "opening": 25.9,
    "location": "F1A23",
    "reservation": null
  },
  {
    "tally": null,
    "material": "COMPOUND SR",
    "brand": null,
    "packing": 25,
    "article": null,
    "packingDetail": "4×25kg",
    "totalStock": 100,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 100,
    "location": "F1A23",
    "reservation": null
  },
  {
    "tally": null,
    "material": "LAKE BRILLIANT BLUE FCF",
    "brand": "VIDDHI",
    "packing": 12.5,
    "article": null,
    "packingDetail": "2×12.5kg",
    "totalStock": 25,
    "batchNo": "LBBM3902",
    "mfg": "2022-08-03",
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 25,
    "location": "F1A25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "EW ORCHID RF 22211108",
    "brand": null,
    "packing": 25,
    "article": null,
    "packingDetail": "12×25kg",
    "totalStock": 300,
    "batchNo": "GT9162",
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 300,
    "location": "F1A25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BARBEQUE FLAVOR",
    "brand": "AARAV",
    "packing": 25,
    "article": null,
    "packingDetail": "1×25kg",
    "totalStock": 25,
    "batchNo": "FGFLW24-02026",
    "mfg": "2024-12-01",
    "exp": "2026-06-01",
    "in": 0,
    "out": 0,
    "opening": 25,
    "location": "F1A25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BARBEQUE FLAVOR",
    "brand": "AARAV",
    "packing": 25,
    "article": null,
    "packingDetail": "2×25kg",
    "totalStock": 50,
    "batchNo": "FGFLW25-00307",
    "mfg": "2025-02-01",
    "exp": "2026-08-01",
    "in": 0,
    "out": 0,
    "opening": 50,
    "location": "F1A25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "RASPBERRY - G - 80842",
    "brand": "GOLDEN",
    "packing": 25,
    "article": null,
    "packingDetail": "3×25kg",
    "totalStock": 75,
    "batchNo": "072410",
    "mfg": "2024-07-09",
    "exp": "2026-07-09",
    "in": 0,
    "out": 0,
    "opening": 75,
    "location": "F1A25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "RASPBERRY - G - 80842",
    "brand": "GOLDEN",
    "packing": 25,
    "article": null,
    "packingDetail": "1×25kg",
    "totalStock": 25,
    "batchNo": "092304",
    "mfg": "2023-09-01",
    "exp": "2025-09-01",
    "in": 0,
    "out": 0,
    "opening": 25,
    "location": "F1A25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ZTX",
    "brand": "HEMANI",
    "packing": null,
    "article": null,
    "packingDetail": "24.9kg loose",
    "totalStock": 24.9,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 24.9,
    "location": "F1A25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ZTX",
    "brand": "HEMANI",
    "packing": null,
    "article": null,
    "packingDetail": "17.6kg loose",
    "totalStock": 17.6,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 17.6,
    "location": "F1A25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "HONEY - G - 89865",
    "brand": "GOLDEN",
    "packing": 25,
    "article": null,
    "packingDetail": "3×25kg",
    "totalStock": 75,
    "batchNo": "072411",
    "mfg": "2024-07-09",
    "exp": "2026-07-09",
    "in": 0,
    "out": 0,
    "opening": 75,
    "location": "F1A25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "HONEY - G - 89865",
    "brand": "GOLDEN",
    "packing": 25,
    "article": null,
    "packingDetail": "1×25kg",
    "totalStock": 25,
    "batchNo": "092305",
    "mfg": "2023-09-01",
    "exp": "2025-09-01",
    "in": 0,
    "out": 0,
    "opening": 25,
    "location": "F1A25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "FIRDAUS - 0144",
    "brand": "IMPERIAL",
    "packing": 25,
    "article": null,
    "packingDetail": "2×25kg",
    "totalStock": 50,
    "batchNo": "IF/375609",
    "mfg": "2026-04-18",
    "exp": "2027-10-17",
    "in": 0,
    "out": 0,
    "opening": 50,
    "location": "F1A25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GALAXOLIDE 50%",
    "brand": "(OLD)",
    "packing": 30,
    "article": null,
    "packingDetail": "1×30kg",
    "totalStock": 30,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 30,
    "location": "F1A25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ALPHA IONONE",
    "brand": null,
    "packing": 30,
    "article": null,
    "packingDetail": "2×30kg",
    "totalStock": 60,
    "batchNo": "0826010012",
    "mfg": "2026-01-27",
    "exp": "2028-01-26",
    "in": 0,
    "out": 0,
    "opening": 60,
    "location": "F1A26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "LOREXAN",
    "brand": "KAROMAS",
    "packing": null,
    "article": null,
    "packingDetail": "7.93kg loose",
    "totalStock": 7.93,
    "batchNo": "LN060121",
    "mfg": "2025-06-09",
    "exp": "2027-06-09",
    "in": 0,
    "out": 0,
    "opening": 7.93,
    "location": "F1A26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "LOREXAN",
    "brand": "KAROMAS",
    "packing": 25,
    "article": null,
    "packingDetail": "1×25kg",
    "totalStock": 25,
    "batchNo": "LN060121",
    "mfg": "2025-06-09",
    "exp": "2027-06-09",
    "in": 0,
    "out": 0,
    "opening": 25,
    "location": "F1A26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BENZYL PROPIONATE",
    "brand": "JAYSHREE",
    "packing": null,
    "article": null,
    "packingDetail": "1.6kg loose",
    "totalStock": 1.6,
    "batchNo": "2025051101R-100",
    "mfg": "2025-05-11",
    "exp": "2026-05-10",
    "in": 0,
    "out": 0,
    "opening": 1.6,
    "location": "F1A26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "EUGENOL",
    "brand": "KRYSTAL",
    "packing": 25,
    "article": null,
    "packingDetail": "3×25kg",
    "totalStock": 75,
    "batchNo": "DK2605015",
    "mfg": "2026-05-12",
    "exp": "2028-05-11",
    "in": 0,
    "out": 0,
    "opening": 75,
    "location": "F1A26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "EUGENOL",
    "brand": "KRYSTAL",
    "packing": null,
    "article": null,
    "packingDetail": "18.5kg loose",
    "totalStock": 18.5,
    "batchNo": "DK2605015",
    "mfg": "2026-05-12",
    "exp": "2028-05-11",
    "in": 0,
    "out": 0,
    "opening": 18.5,
    "location": "F1A26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "SANDELLA IBCH",
    "brand": "KLP",
    "packing": null,
    "article": null,
    "packingDetail": "0.5kg loose",
    "totalStock": 0.5,
    "batchNo": "260419",
    "mfg": "2026-04-19",
    "exp": "2028-04-18",
    "in": 0,
    "out": 0,
    "opening": 0.5,
    "location": "F1A26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "SANDELLA IBCH",
    "brand": "KLP",
    "packing": null,
    "article": null,
    "packingDetail": "0.8kg loose",
    "totalStock": 0.8,
    "batchNo": "260607",
    "mfg": "2026-06-07",
    "exp": "2028-06-06",
    "in": 0,
    "out": 0,
    "opening": 0.8,
    "location": "F1A26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DIHYDROROSAN",
    "brand": "BASF",
    "packing": 30,
    "article": null,
    "packingDetail": "1×30kg",
    "totalStock": 30,
    "batchNo": "80498797V0",
    "mfg": "2023-10-12",
    "exp": "2027-10-12",
    "in": 0,
    "out": 0,
    "opening": 30,
    "location": "F1A26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DIHYDROROSAN",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "29.98kg loose",
    "totalStock": 29.98,
    "batchNo": "80498797V0",
    "mfg": "2023-10-12",
    "exp": "2027-10-12",
    "in": 0,
    "out": 0,
    "opening": 29.98,
    "location": "F1A26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DIHYDROROSAN",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "7.78kg loose",
    "totalStock": 7.78,
    "batchNo": "80498797V0",
    "mfg": "2023-10-12",
    "exp": "2027-10-12",
    "in": 0,
    "out": 0,
    "opening": 7.78,
    "location": "F1A26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "FLORALOZONE",
    "brand": "FINE FRAGRANCE",
    "packing": null,
    "article": null,
    "packingDetail": "0.8kg loose",
    "totalStock": 0.8,
    "batchNo": "LN060234",
    "mfg": "2023-12-01",
    "exp": "2025-12-01",
    "in": 0,
    "out": 0,
    "opening": 0.8,
    "location": "F1A26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "FLORALOZONE",
    "brand": "FINE FRAGRANCE",
    "packing": null,
    "article": null,
    "packingDetail": "1kg loose",
    "totalStock": 1,
    "batchNo": "LN060234",
    "mfg": "2023-12-01",
    "exp": "2025-12-01",
    "in": 0,
    "out": 0,
    "opening": 1,
    "location": "F1A26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NAGARMOTHA OIL",
    "brand": null,
    "packing": 5,
    "article": null,
    "packingDetail": "2×5kg",
    "totalStock": 10,
    "batchNo": "NM2589B011",
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 10,
    "location": "F1A26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NAGARMOTHA OIL",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "2×1kg loose",
    "totalStock": 2,
    "batchNo": "NM2589B011",
    "mfg": "2026-06-07",
    "exp": "2028-06-02",
    "in": 0,
    "out": 0,
    "opening": 2,
    "location": "F1A26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NAGARMOTHA OIL",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "0.8kg loose",
    "totalStock": 0.8,
    "batchNo": "NM2848B020",
    "mfg": "2026-06-07",
    "exp": "2028-06-02",
    "in": 0,
    "out": 0,
    "opening": 0.8,
    "location": "F1A26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NAGARMOTHA OIL",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "0.33kg loose",
    "totalStock": 0.33,
    "batchNo": "NM25875BEX475",
    "mfg": "2023-02-18",
    "exp": "2025-02-17",
    "in": 0,
    "out": 0,
    "opening": 0.33,
    "location": "F1A26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NAGARMOTHA OIL",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "0.06kg loose",
    "totalStock": 0.06,
    "batchNo": "NM2855BS04",
    "mfg": "2023-02-18",
    "exp": "2025-02-17",
    "in": 0,
    "out": 0,
    "opening": 0.06,
    "location": "F1A26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GERANIUM OIL EGYPT",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "0.1kg loose",
    "totalStock": 0.1,
    "batchNo": "D22-032-Z",
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 0.1,
    "location": "F1A26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "LABDANUM RES/OA",
    "brand": "OPUS",
    "packing": 20,
    "article": null,
    "packingDetail": "1×20kg",
    "totalStock": 20,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 20,
    "location": "F1A27",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BENZOIN OA",
    "brand": "OPUS",
    "packing": 20,
    "article": null,
    "packingDetail": "1×20kg",
    "totalStock": 20,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 20,
    "location": "F1A27",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CASTORSUN RES/OA",
    "brand": null,
    "packing": 1,
    "article": null,
    "packingDetail": "5×1kg",
    "totalStock": 5,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 5,
    "location": "F1A27",
    "reservation": null
  },
  {
    "tally": null,
    "material": "HYDROXENE",
    "brand": null,
    "packing": 5,
    "article": null,
    "packingDetail": "4×5kg",
    "totalStock": 20,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 20,
    "location": "F1A27",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GERANIUM DGS",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "15kg loose",
    "totalStock": 15,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 15,
    "location": "F1A27",
    "reservation": null
  },
  {
    "tally": null,
    "material": "LAVENDIN",
    "brand": null,
    "packing": 5,
    "article": null,
    "packingDetail": "2×5kg",
    "totalStock": 10,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 10,
    "location": "F1A27",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NUTMEG OIL",
    "brand": "KANCOR",
    "packing": 25,
    "article": null,
    "packingDetail": "4×25kg",
    "totalStock": 100,
    "batchNo": "NTO238028",
    "mfg": "2026-06-04",
    "exp": "2028-06-03",
    "in": 0,
    "out": 0,
    "opening": 100,
    "location": "F1B1",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NUTMEG OIL",
    "brand": "KANCOR",
    "packing": 25,
    "article": null,
    "packingDetail": "1×25kg",
    "totalStock": 25,
    "batchNo": "NTO237115",
    "mfg": "2026-03-02",
    "exp": "2028-03-01",
    "in": 0,
    "out": 0,
    "opening": 25,
    "location": "F1B1",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NUTMEG OIL",
    "brand": "KANCOR",
    "packing": null,
    "article": null,
    "packingDetail": "8.32kg loose",
    "totalStock": 8.32,
    "batchNo": "NTO237115",
    "mfg": "2026-03-02",
    "exp": "2028-03-01",
    "in": 0,
    "out": 0,
    "opening": 8.32,
    "location": "F1B1",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NUTMEG OIL",
    "brand": "KANCOR",
    "packing": 25,
    "article": null,
    "packingDetail": "2×25kg",
    "totalStock": 50,
    "batchNo": "NTO238266",
    "mfg": "2026-06-26",
    "exp": "2028-06-25",
    "in": 0,
    "out": 0,
    "opening": 50,
    "location": "F1B1",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NUTMEG OIL",
    "brand": "KANCOR",
    "packing": 25,
    "article": null,
    "packingDetail": "2×25kg",
    "totalStock": 50,
    "batchNo": "NTO237645",
    "mfg": "2026-04-25",
    "exp": "2028-04-24",
    "in": 0,
    "out": 0,
    "opening": 50,
    "location": "F1B1",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NUTMEG OIL",
    "brand": "KANCOR",
    "packing": 25,
    "article": null,
    "packingDetail": "4×25kg",
    "totalStock": 100,
    "batchNo": "NTO238521",
    "mfg": "2026-07-24",
    "exp": "2028-07-23",
    "in": 0,
    "out": 0,
    "opening": 100,
    "location": "F1B1",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NUTMEG OIL",
    "brand": "KANCOR",
    "packing": 25,
    "article": null,
    "packingDetail": "4×25kg",
    "totalStock": 100,
    "batchNo": "NTO238428",
    "mfg": "2026-07-15",
    "exp": "2028-07-14",
    "in": 0,
    "out": 0,
    "opening": 100,
    "location": "F1B1",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NUTMEG OIL",
    "brand": "KANCOR",
    "packing": null,
    "article": null,
    "packingDetail": "4kg loose",
    "totalStock": 4,
    "batchNo": "NTO236294",
    "mfg": "2025-11-28",
    "exp": "2027-11-27",
    "in": 0,
    "out": 0,
    "opening": 4,
    "location": "F1B1",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NUTMEG OIL",
    "brand": "KANCOR",
    "packing": null,
    "article": null,
    "packingDetail": "0.96kg loose",
    "totalStock": 0.96,
    "batchNo": "NTO235072",
    "mfg": "2025-06-25",
    "exp": "2027-06-24",
    "in": 0,
    "out": 0,
    "opening": 0.96,
    "location": "F1B1",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NUTMEG OIL",
    "brand": "GREEN LEAF",
    "packing": null,
    "article": null,
    "packingDetail": "2×1kg loose",
    "totalStock": 2,
    "batchNo": "77603",
    "mfg": "2023-12-19",
    "exp": "2026-12-17",
    "in": 0,
    "out": 0,
    "opening": 2,
    "location": "F1B1",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NUTMEG OIL",
    "brand": "GREEN LEAF",
    "packing": null,
    "article": null,
    "packingDetail": "0.04kg loose",
    "totalStock": 0.04,
    "batchNo": "77603",
    "mfg": "2023-12-19",
    "exp": "2026-12-17",
    "in": 0,
    "out": 0,
    "opening": 0.04,
    "location": "F1B1",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NUTMEG OIL",
    "brand": "GREEN LEAF",
    "packing": null,
    "article": null,
    "packingDetail": "0.3kg loose",
    "totalStock": 0.3,
    "batchNo": "69028",
    "mfg": "2023-02-18",
    "exp": "2026-02-17",
    "in": 0,
    "out": 0,
    "opening": 0.3,
    "location": "F1B1",
    "reservation": null
  },
  {
    "tally": null,
    "material": "LEMONGRASS OIL",
    "brand": "KANCOR",
    "packing": null,
    "article": null,
    "packingDetail": "0.919kg loose",
    "totalStock": 0.919,
    "batchNo": "LGO237758",
    "mfg": "2026-05-08",
    "exp": "2028-05-07",
    "in": 0,
    "out": 0,
    "opening": 0.919,
    "location": "F1B2",
    "reservation": null
  },
  {
    "tally": null,
    "material": "LEMONGRASS OIL",
    "brand": "KANCOR",
    "packing": null,
    "article": null,
    "packingDetail": "2×1kg loose",
    "totalStock": 2,
    "batchNo": "LGO237758",
    "mfg": "2026-05-08",
    "exp": "2028-05-07",
    "in": 0,
    "out": 0,
    "opening": 2,
    "location": "F1B2",
    "reservation": null
  },
  {
    "tally": null,
    "material": "VETIVER OIL",
    "brand": "KANCOR",
    "packing": null,
    "article": null,
    "packingDetail": "0.29kg loose",
    "totalStock": 0.29,
    "batchNo": "VET233817",
    "mfg": "2025-02-11",
    "exp": "2027-02-10",
    "in": 0,
    "out": 0,
    "opening": 0.29,
    "location": "F1B2",
    "reservation": null
  },
  {
    "tally": null,
    "material": "TURMERIC OIL",
    "brand": "KANCOR",
    "packing": null,
    "article": null,
    "packingDetail": "0.055kg loose",
    "totalStock": 0.055,
    "batchNo": "TUOE234387",
    "mfg": "2025-04-11",
    "exp": "2027-04-10",
    "in": 0,
    "out": 0,
    "opening": 0.055,
    "location": "F1B2",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BENZYL ALCOHOL",
    "brand": "LNX",
    "packing": 35,
    "article": null,
    "packingDetail": "1×35kg",
    "totalStock": 35,
    "batchNo": "LN060190",
    "mfg": "2026-04-13",
    "exp": "2027-04-13",
    "in": 0,
    "out": 0,
    "opening": 35,
    "location": "F1B17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BENZYL ALCOHOL",
    "brand": "LNX",
    "packing": null,
    "article": null,
    "packingDetail": "22.9kg loose",
    "totalStock": 22.9,
    "batchNo": "LN060190",
    "mfg": "2026-04-13",
    "exp": "2027-04-13",
    "in": 0,
    "out": 0,
    "opening": 22.9,
    "location": "F1B17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PADMA",
    "brand": "AQUILA",
    "packing": 1,
    "article": null,
    "packingDetail": "1×1kg",
    "totalStock": 1,
    "batchNo": "013/014/09/25",
    "mfg": "2025-09-26",
    "exp": "2026-03-32",
    "in": 0,
    "out": 0,
    "opening": 1,
    "location": "F1B17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PADMA",
    "brand": "AQUILA",
    "packing": null,
    "article": null,
    "packingDetail": "1.24kg loose",
    "totalStock": 1.24,
    "batchNo": "LN060222",
    "mfg": "2026-05-05",
    "exp": "2027-05-04",
    "in": 0,
    "out": 0,
    "opening": 1.24,
    "location": "F1B17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PADMA",
    "brand": "AQUILA",
    "packing": null,
    "article": null,
    "packingDetail": "0.32kg loose",
    "totalStock": 0.32,
    "batchNo": "LN060222",
    "mfg": "2026-05-05",
    "exp": "2027-05-04",
    "in": 0,
    "out": 0,
    "opening": 0.32,
    "location": "F1B17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PHENYL ACETALDEHYDE 50% DEP",
    "brand": "FS (REJECT)",
    "packing": 25,
    "article": null,
    "packingDetail": "5×25kg",
    "totalStock": 125,
    "batchNo": "1498/10092025",
    "mfg": "2025-09-10",
    "exp": "2026-03-09",
    "in": 0,
    "out": 0,
    "opening": 125,
    "location": "F1B17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PHENYL ACETALDEHYDE 50% DEP",
    "brand": "FS (REJECT)",
    "packing": null,
    "article": null,
    "packingDetail": "4.95kg loose",
    "totalStock": 4.95,
    "batchNo": "1498/10092025",
    "mfg": "2025-09-10",
    "exp": "2026-03-09",
    "in": 0,
    "out": 0,
    "opening": 4.95,
    "location": "F1B17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PHENYL ACETALDEHYDE 50% DEP",
    "brand": "FS",
    "packing": null,
    "article": null,
    "packingDetail": "15kg loose",
    "totalStock": 15,
    "batchNo": "1498/10092025",
    "mfg": "2025-09-10",
    "exp": "2026-03-09",
    "in": 0,
    "out": 0,
    "opening": 15,
    "location": "F1B17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PHENYL ACETALDEHYDE 50% DEP",
    "brand": "FS",
    "packing": null,
    "article": null,
    "packingDetail": "0.6kg loose",
    "totalStock": 0.6,
    "batchNo": "1076/1505/2024",
    "mfg": "2024-05-14",
    "exp": "2026-05-14",
    "in": 0,
    "out": 0,
    "opening": 0.6,
    "location": "F1B17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PHENYL ACETALDEHYDE 50% DEP",
    "brand": "FS",
    "packing": null,
    "article": null,
    "packingDetail": "1.9kg loose",
    "totalStock": 1.9,
    "batchNo": "1377/17052025",
    "mfg": "2025-05-17",
    "exp": "2025-11-16",
    "in": 0,
    "out": 0,
    "opening": 1.9,
    "location": "F1B17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "LILIANTHRAL",
    "brand": "FS",
    "packing": null,
    "article": null,
    "packingDetail": "10kg loose",
    "totalStock": 10,
    "batchNo": "136/24052025",
    "mfg": "2025-05-22",
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 10,
    "location": "F1B17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AURANTINE",
    "brand": "FS (QC NOT OK)",
    "packing": 5,
    "article": null,
    "packingDetail": "2×5kg",
    "totalStock": 10,
    "batchNo": "115/08072024",
    "mfg": "2024-07-02",
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 10,
    "location": "F1B17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ETHYL BUTYRATE",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "30.5kg loose",
    "totalStock": 30.5,
    "batchNo": "L060199",
    "mfg": "2026-04-24",
    "exp": "2027-04-23",
    "in": 0,
    "out": 0,
    "opening": 30.5,
    "location": "F1B17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ETHYL BUTYRATE",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "29.85kg loose",
    "totalStock": 29.85,
    "batchNo": "L060199",
    "mfg": "2026-04-24",
    "exp": "2027-04-23",
    "in": 0,
    "out": 0,
    "opening": 29.85,
    "location": "F1B17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ETHYL BUTYRATE",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "29.9kg loose",
    "totalStock": 29.9,
    "batchNo": "L060199",
    "mfg": "2026-04-24",
    "exp": "2027-04-23",
    "in": 0,
    "out": 0,
    "opening": 29.9,
    "location": "F1B17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ETHYL BUTYRATE",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "1.13kg loose",
    "totalStock": 1.13,
    "batchNo": "2023012",
    "mfg": "2023-06-01",
    "exp": "2025-01-01",
    "in": 0,
    "out": 0,
    "opening": 1.13,
    "location": "F1B17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DI PHENYL OXIDE/DPO",
    "brand": "KDAC",
    "packing": null,
    "article": null,
    "packingDetail": "3.2kg loose",
    "totalStock": 3.2,
    "batchNo": "28./12",
    "mfg": "2022-12-01",
    "exp": "2024-11-01",
    "in": 0,
    "out": 0,
    "opening": 3.2,
    "location": "F1B18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DI PHENYL OXIDE/DPO",
    "brand": "KDAC",
    "packing": null,
    "article": null,
    "packingDetail": "6kg loose",
    "totalStock": 6,
    "batchNo": "20./10",
    "mfg": "2024-10-01",
    "exp": "2026-10-01",
    "in": 0,
    "out": 0,
    "opening": 6,
    "location": "F1B18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DI PHENYL OXIDE/DPO",
    "brand": "HJ",
    "packing": null,
    "article": null,
    "packingDetail": "8.3kg loose",
    "totalStock": 8.3,
    "batchNo": "250913/1",
    "mfg": "2025-09-01",
    "exp": "2027-09-01",
    "in": 0,
    "out": 0,
    "opening": 8.3,
    "location": "F1B18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DI PHENYL OXIDE/DPO",
    "brand": "HJ",
    "packing": null,
    "article": null,
    "packingDetail": "3.8kg loose",
    "totalStock": 3.8,
    "batchNo": "241206",
    "mfg": "2024-12-01",
    "exp": "2026-12-01",
    "in": 0,
    "out": 0,
    "opening": 3.8,
    "location": "F1B18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DI PHENYL OXIDE/DPO",
    "brand": "HJ",
    "packing": null,
    "article": null,
    "packingDetail": "2.7kg loose",
    "totalStock": 2.7,
    "batchNo": "260223",
    "mfg": "2026-02-01",
    "exp": "2028-02-01",
    "in": 0,
    "out": 0,
    "opening": 2.7,
    "location": "F1B18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DI PHENYL OXIDE/DPO",
    "brand": "HEMANI",
    "packing": null,
    "article": null,
    "packingDetail": "3kg loose",
    "totalStock": 3,
    "batchNo": "260223",
    "mfg": "2026-02-01",
    "exp": "2028-02-01",
    "in": 0,
    "out": 0,
    "opening": 3,
    "location": "F1B18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DI PHENYL OXIDE/DPO",
    "brand": "PRAKASH",
    "packing": 30,
    "article": null,
    "packingDetail": "4×30kg",
    "totalStock": 120,
    "batchNo": ",10010700000050",
    "mfg": "2025-11-30",
    "exp": "2027-11-30",
    "in": 0,
    "out": 0,
    "opening": 120,
    "location": "F1B18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DI PHENYL OXIDE/DPO",
    "brand": "PRAKASH",
    "packing": null,
    "article": null,
    "packingDetail": "24.38kg loose",
    "totalStock": 24.38,
    "batchNo": ",10010700000050",
    "mfg": "2025-11-30",
    "exp": "2027-11-30",
    "in": 0,
    "out": 0,
    "opening": 24.38,
    "location": "F1B18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BENZYL ACETATE",
    "brand": "LNX",
    "packing": null,
    "article": null,
    "packingDetail": "14.25kg loose",
    "totalStock": 14.25,
    "batchNo": "26BAC023D",
    "mfg": "2026-02-13",
    "exp": "2027-02-13",
    "in": 0,
    "out": 0,
    "opening": 14.25,
    "location": "F1B18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BENZYL ACETATE",
    "brand": "LNX",
    "packing": null,
    "article": null,
    "packingDetail": "1.35kg loose",
    "totalStock": 1.35,
    "batchNo": "24BAC131D",
    "mfg": "2026-02-13",
    "exp": "2027-02-13",
    "in": 0,
    "out": 0,
    "opening": 1.35,
    "location": "F1B18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BENZYL ACETATE",
    "brand": "LNX",
    "packing": null,
    "article": null,
    "packingDetail": "1.1kg loose",
    "totalStock": 1.1,
    "batchNo": "LN060240",
    "mfg": "2026-06-07",
    "exp": "2027-06-06",
    "in": 0,
    "out": 0,
    "opening": 1.1,
    "location": "F1B18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PATCHOULI OIL 30+",
    "brand": "VAN",
    "packing": null,
    "article": null,
    "packingDetail": "1.75kg loose",
    "totalStock": 1.75,
    "batchNo": "25110282-1",
    "mfg": "2025-11-26",
    "exp": "2028-11-25",
    "in": 0,
    "out": 0,
    "opening": 1.75,
    "location": "F1B18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PATCHOULI OIL 30+",
    "brand": "VAN (RESERVE)",
    "packing": 25,
    "article": null,
    "packingDetail": "5×25kg",
    "totalStock": 125,
    "batchNo": "26040100-1",
    "mfg": "2026-04-07",
    "exp": "2029-04-06",
    "in": 0,
    "out": 0,
    "opening": 125,
    "location": "F1B18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PATCHOULI OIL 30+",
    "brand": "VAN",
    "packing": null,
    "article": null,
    "packingDetail": "4.1kg loose",
    "totalStock": 4.1,
    "batchNo": "26040100-1",
    "mfg": "2026-04-07",
    "exp": "2029-04-06",
    "in": 0,
    "out": 0,
    "opening": 4.1,
    "location": "F1B18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PATCHOULI OIL 30+",
    "brand": "VAN",
    "packing": null,
    "article": null,
    "packingDetail": "9.3kg loose",
    "totalStock": 9.3,
    "batchNo": "26040100-1",
    "mfg": "2026-04-07",
    "exp": "2029-04-06",
    "in": 0,
    "out": 0,
    "opening": 9.3,
    "location": "F1B18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NEROLIN BROMELIA",
    "brand": "O",
    "packing": 20,
    "article": null,
    "packingDetail": "1×20kg",
    "totalStock": 20,
    "batchNo": "V26F007252",
    "mfg": "2026-06-18",
    "exp": "2027-06-17",
    "in": 0,
    "out": 0,
    "opening": 20,
    "location": "F1B19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NEROLIN BROMELIA",
    "brand": "O",
    "packing": null,
    "article": null,
    "packingDetail": "15kg loose",
    "totalStock": 15,
    "batchNo": "V26F007252",
    "mfg": "2026-06-18",
    "exp": "2027-06-17",
    "in": 0,
    "out": 0,
    "opening": 15,
    "location": "F1B19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NEROLIN BROMELIA",
    "brand": "O",
    "packing": null,
    "article": null,
    "packingDetail": "4.9kg loose",
    "totalStock": 4.9,
    "batchNo": "V26F006813",
    "mfg": "2026-03-17",
    "exp": "2027-03-16",
    "in": 0,
    "out": 0,
    "opening": 4.9,
    "location": "F1B19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NEROLIN BROMELIA",
    "brand": "O",
    "packing": null,
    "article": null,
    "packingDetail": "0.4kg loose",
    "totalStock": 0.4,
    "batchNo": "V24F003582",
    "mfg": "2024-09-26",
    "exp": "2025-09-25",
    "in": 0,
    "out": 0,
    "opening": 0.4,
    "location": "F1B19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NEROLIN BROMELIA",
    "brand": "O",
    "packing": null,
    "article": null,
    "packingDetail": "0.3kg loose",
    "totalStock": 0.3,
    "batchNo": "V25F004186",
    "mfg": "2024-12-29",
    "exp": "2025-12-28",
    "in": 0,
    "out": 0,
    "opening": 0.3,
    "location": "F1B19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "SKATOL",
    "brand": "SUMAN",
    "packing": null,
    "article": null,
    "packingDetail": "4.95kg loose",
    "totalStock": 4.95,
    "batchNo": "LN060140",
    "mfg": "2025-08-17",
    "exp": "2027-08-16",
    "in": 0,
    "out": 0,
    "opening": 4.95,
    "location": "F1B19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "SKATOL",
    "brand": "SUMAN",
    "packing": null,
    "article": null,
    "packingDetail": "3.2kg loose",
    "totalStock": 3.2,
    "batchNo": "LN060140",
    "mfg": "2025-08-17",
    "exp": "2027-08-16",
    "in": 0,
    "out": 0,
    "opening": 3.2,
    "location": "F1B19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BVSON AVB",
    "brand": "BVC",
    "packing": 25,
    "article": null,
    "packingDetail": "4×25kg",
    "totalStock": 100,
    "batchNo": "C166640859",
    "mfg": "2025-08-12",
    "exp": "2027-08-12",
    "in": 0,
    "out": 0,
    "opening": 100,
    "location": "F1B13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PTBCH",
    "brand": "E",
    "packing": 25,
    "article": null,
    "packingDetail": "1×25kg",
    "totalStock": 25,
    "batchNo": "1074JC2017",
    "mfg": "2026-03-30",
    "exp": "2028-03-29",
    "in": 0,
    "out": 0,
    "opening": 25,
    "location": "F1B13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PTBCH",
    "brand": "E",
    "packing": null,
    "article": null,
    "packingDetail": "1.4kg loose",
    "totalStock": 1.4,
    "batchNo": "1074HG2018",
    "mfg": "2024-07-30",
    "exp": "2026-07-30",
    "in": 0,
    "out": 0,
    "opening": 1.4,
    "location": "F1B13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GERANYL PROPIONATE",
    "brand": "JY",
    "packing": 30,
    "article": null,
    "packingDetail": "1×30kg",
    "totalStock": 30,
    "batchNo": "LN060188",
    "mfg": "2026-04-02",
    "exp": "2027-04-01",
    "in": 0,
    "out": 0,
    "opening": 30,
    "location": "F1B13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GERANYL PROPIONATE",
    "brand": "JY",
    "packing": null,
    "article": null,
    "packingDetail": "15kg loose",
    "totalStock": 15,
    "batchNo": "LN060188",
    "mfg": "2026-04-02",
    "exp": "2027-04-01",
    "in": 0,
    "out": 0,
    "opening": 15,
    "location": "F1B13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CYCLAMEN ALDEHYDE",
    "brand": "Givdan",
    "packing": 10,
    "article": null,
    "packingDetail": "1×10kg",
    "totalStock": 10,
    "batchNo": "PE00399823",
    "mfg": "2024-05-30",
    "exp": "2026-05-25",
    "in": 0,
    "out": 0,
    "opening": 10,
    "location": "F1B13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CYCLAMEN ALDEHYDE",
    "brand": "Givdan",
    "packing": null,
    "article": null,
    "packingDetail": "3.4kg loose",
    "totalStock": 3.4,
    "batchNo": "PE00399823",
    "mfg": "2024-05-30",
    "exp": "2026-05-25",
    "in": 0,
    "out": 0,
    "opening": 3.4,
    "location": "F1B13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CYCLAMEN ALDEHYDE",
    "brand": "E",
    "packing": null,
    "article": null,
    "packingDetail": "14.77kg loose",
    "totalStock": 14.77,
    "batchNo": "1040JC1013",
    "mfg": "2026-03-22",
    "exp": "2027-03-22",
    "in": 0,
    "out": 0,
    "opening": 14.77,
    "location": "F1B13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CYCLAMEN ALDEHYDE",
    "brand": "E",
    "packing": null,
    "article": null,
    "packingDetail": "0.54kg loose",
    "totalStock": 0.54,
    "batchNo": "1040IH1005",
    "mfg": "2025-08-06",
    "exp": "2026-08-06",
    "in": 0,
    "out": 0,
    "opening": 0.54,
    "location": "F1B13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "METHYL CINNAMATE",
    "brand": "FOC",
    "packing": null,
    "article": null,
    "packingDetail": "3.98kg loose",
    "totalStock": 3.98,
    "batchNo": "LN060173",
    "mfg": "2026-04-13",
    "exp": "2027-04-12",
    "in": 0,
    "out": 0,
    "opening": 3.98,
    "location": "F1B13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "METHYL CINNAMATE",
    "brand": "FOC",
    "packing": null,
    "article": null,
    "packingDetail": "3.9kg loose",
    "totalStock": 3.9,
    "batchNo": "LN060173",
    "mfg": "2026-04-13",
    "exp": "2027-04-12",
    "in": 0,
    "out": 0,
    "opening": 3.9,
    "location": "F1B13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "METHYL CINNAMATE",
    "brand": "ROMA",
    "packing": null,
    "article": null,
    "packingDetail": "1kg loose",
    "totalStock": 1,
    "batchNo": "20240916142",
    "mfg": "2024-06-10",
    "exp": "2025-06-09",
    "in": 0,
    "out": 0,
    "opening": 1,
    "location": "F1B13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "METHYL CINNAMATE",
    "brand": "AAPL",
    "packing": null,
    "article": null,
    "packingDetail": "0.3kg loose",
    "totalStock": 0.3,
    "batchNo": "20241106",
    "mfg": "2024-06-01",
    "exp": "2026-06-01",
    "in": 0,
    "out": 0,
    "opening": 0.3,
    "location": "F1B13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "METHYL CINNAMATE",
    "brand": "AAPL",
    "packing": null,
    "article": null,
    "packingDetail": "0.9kg loose",
    "totalStock": 0.9,
    "batchNo": "20241106",
    "mfg": "2024-06-01",
    "exp": "2026-06-01",
    "in": 0,
    "out": 0,
    "opening": 0.9,
    "location": "F1B13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "METHYL CINNAMATE",
    "brand": "C",
    "packing": 25,
    "article": null,
    "packingDetail": "1×25kg",
    "totalStock": 25,
    "batchNo": "20251226001",
    "mfg": "2025-12-26",
    "exp": "2026-12-25",
    "in": 0,
    "out": 0,
    "opening": 25,
    "location": "F1B13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "METHYL CINNAMATE",
    "brand": "ROMA (REJECT)",
    "packing": null,
    "article": null,
    "packingDetail": "24.57kg loose",
    "totalStock": 24.57,
    "batchNo": "20211004002",
    "mfg": "2022-09-14",
    "exp": "2023-09-13",
    "in": 0,
    "out": 0,
    "opening": 24.57,
    "location": "F1B13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "METHYL CINNAMATE",
    "brand": "AAPL",
    "packing": null,
    "article": null,
    "packingDetail": "1.5kg loose",
    "totalStock": 1.5,
    "batchNo": "20241106",
    "mfg": "2024-06-01",
    "exp": "2026-06-01",
    "in": 0,
    "out": 0,
    "opening": 1.5,
    "location": "F1B13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BOISE DE ROSE",
    "brand": "BMV",
    "packing": 30,
    "article": null,
    "packingDetail": "1×30kg",
    "totalStock": 30,
    "batchNo": "01/2026/01/0220",
    "mfg": "2026-01-01",
    "exp": "2027-12-01",
    "in": 0,
    "out": 0,
    "opening": 30,
    "location": "F1B13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BOISE DE ROSE",
    "brand": "BMV",
    "packing": null,
    "article": null,
    "packingDetail": "15kg loose",
    "totalStock": 15,
    "batchNo": "01/2026/01/0220",
    "mfg": "2026-01-01",
    "exp": "2027-12-01",
    "in": 0,
    "out": 0,
    "opening": 15,
    "location": "F1B13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BOISE DE ROSE",
    "brand": "BOTOX",
    "packing": null,
    "article": null,
    "packingDetail": "0.46kg loose",
    "totalStock": 0.46,
    "batchNo": "1004190",
    "mfg": "2026-01-01",
    "exp": "2027-12-01",
    "in": 0,
    "out": 0,
    "opening": 0.46,
    "location": "F1B13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ETHYL CINNAMTE",
    "brand": "ROMA",
    "packing": null,
    "article": null,
    "packingDetail": "0.5kg loose",
    "totalStock": 0.5,
    "batchNo": "20240813133",
    "mfg": "2025-02-13",
    "exp": "2026-02-12",
    "in": 0,
    "out": 0,
    "opening": 0.5,
    "location": "F1B13",
    "reservation": null
  }
];

export const NEW_LOCATIONS = [
  "F1A21",
  "F1A22",
  "F1A23",
  "F1A25",
  "F1A26",
  "F1A27",
  "F1B1",
  "F1B13",
  "F1B17",
  "F1B18",
  "F1B19",
  "F1B2"
];
