// Holds only the newest CSV batch to import — replace the contents of NEW_STOCK_ITEMS
// (and NEW_LOCATIONS, if the batch introduces bin codes not already in the DB) each time
// a new stock sheet comes in, then run `npm run import-stock`.
// Current batch: new-stock.csv (143 items).
export const NEW_STOCK_ITEMS = [
  {
    "tally": null,
    "material": "BENZOPHENONE",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "9.4kg loose",
    "totalStock": 9.4,
    "batchNo": "LN060163",
    "mfg": "2026-03-04",
    "exp": "2027-03-03",
    "in": 0,
    "out": 0,
    "opening": 9.4,
    "location": "F1D19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ROSE CRYSTALS",
    "brand": "EX-BENZALDEHYDE",
    "packing": null,
    "article": null,
    "packingDetail": "15kg loose",
    "totalStock": 15,
    "batchNo": "RC0426B-5465",
    "mfg": "2026-04-01",
    "exp": "2027-03-01",
    "in": 0,
    "out": 0,
    "opening": 15,
    "location": "F1D19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ROSE CRYSTALS",
    "brand": "EX-BENZALDEHYDE",
    "packing": null,
    "article": null,
    "packingDetail": "4.3kg loose",
    "totalStock": 4.3,
    "batchNo": "RC0625B",
    "mfg": "2025-06-01",
    "exp": "2027-03-01",
    "in": 0,
    "out": 0,
    "opening": 4.3,
    "location": "F1D19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ROSE CRYSTALS",
    "brand": "SHREE",
    "packing": null,
    "article": null,
    "packingDetail": "10.4kg loose",
    "totalStock": 10.4,
    "batchNo": "19/3",
    "mfg": "2025-03-22",
    "exp": "2027-03-01",
    "in": 0,
    "out": 0,
    "opening": 10.4,
    "location": "F1D19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ROSE CRYSTALS",
    "brand": "EX-BENZALDEHYDE",
    "packing": null,
    "article": null,
    "packingDetail": "10kg loose",
    "totalStock": 10,
    "batchNo": "RC0426B-5465",
    "mfg": "2026-04-01",
    "exp": "2027-03-01",
    "in": 0,
    "out": 0,
    "opening": 10,
    "location": "F1D19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BUTYLATED HYDROXY TOLUENE",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "×16.702kg loose",
    "totalStock": 16.702,
    "batchNo": "BHT0326-13",
    "mfg": "2026-03-27",
    "exp": "2028-03-26",
    "in": 0,
    "out": 0,
    "opening": 16.702,
    "location": "F1D19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "METHYL CEDRYL KETONE",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "10.05kg loose",
    "totalStock": 10.05,
    "batchNo": "BS25100612",
    "mfg": "2025-10-06",
    "exp": "2026-10-06",
    "in": 0,
    "out": 0,
    "opening": 10.05,
    "location": "F1D21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "METHYL CEDRYL KETONE",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "29.77kg loose",
    "totalStock": 29.77,
    "batchNo": "K2601228010-001",
    "mfg": "2026-02-02",
    "exp": "2028-02-01",
    "in": 0,
    "out": 0,
    "opening": 29.77,
    "location": "F1D21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "METHYL CEDRYL KETONE",
    "brand": "CHINA",
    "packing": 30,
    "article": null,
    "packingDetail": "1×30kg",
    "totalStock": 30,
    "batchNo": "K2601228010-001",
    "mfg": "2026-02-02",
    "exp": "2028-02-01",
    "in": 0,
    "out": 0,
    "opening": 30,
    "location": "F1D21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "METHYL CEDRYL KETONE",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "8.57kg loose",
    "totalStock": 8.57,
    "batchNo": "BS25081011",
    "mfg": "2025-08-10",
    "exp": "2026-08-09",
    "in": 0,
    "out": 0,
    "opening": 8.57,
    "location": "F1D21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "METHYL CEDRYL KETONE",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "0.52kg loose",
    "totalStock": 0.52,
    "batchNo": "BS25081011",
    "mfg": "2025-08-10",
    "exp": "2026-08-09",
    "in": 0,
    "out": 0,
    "opening": 0.52,
    "location": "F1D21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ISO AMYL SALICYLATE",
    "brand": "JAYSHREE",
    "packing": 30,
    "article": null,
    "packingDetail": "1×30kg",
    "totalStock": 30,
    "batchNo": "2026021101R-094",
    "mfg": "2026-02-11",
    "exp": "2027-02-10",
    "in": 0,
    "out": 0,
    "opening": 30,
    "location": "F1D21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ISO AMYL SALICYLATE",
    "brand": "JAYSHREE",
    "packing": null,
    "article": null,
    "packingDetail": "29.74kg loose",
    "totalStock": 29.74,
    "batchNo": "2026021101R-094",
    "mfg": "2026-02-11",
    "exp": "2027-02-10",
    "in": 0,
    "out": 0,
    "opening": 29.74,
    "location": "F1D21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ISO AMYL SALICYLATE",
    "brand": "JAYSHREE",
    "packing": null,
    "article": null,
    "packingDetail": "2.57kg loose",
    "totalStock": 2.57,
    "batchNo": "LN060200",
    "mfg": "2026-04-13",
    "exp": "2027-04-12",
    "in": 0,
    "out": 0,
    "opening": 2.57,
    "location": "F1D21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ISO AMYL SALICYLATE",
    "brand": "JAYSHREE",
    "packing": null,
    "article": null,
    "packingDetail": "0.94kg loose",
    "totalStock": 0.94,
    "batchNo": "LN060200",
    "mfg": "2026-04-13",
    "exp": "2027-04-12",
    "in": 0,
    "out": 0,
    "opening": 0.94,
    "location": "F1D21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ISO AMYL SALICYLATE",
    "brand": "JAYSHREE",
    "packing": null,
    "article": null,
    "packingDetail": "0.7kg loose",
    "totalStock": 0.7,
    "batchNo": "2025062901R-386",
    "mfg": "2025-06-29",
    "exp": "2026-06-28",
    "in": 0,
    "out": 0,
    "opening": 0.7,
    "location": "F1D21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "TETRA HYDRO LINALOOL",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "0.97kg loose",
    "totalStock": 0.97,
    "batchNo": "35116247G0",
    "mfg": "2024-07-09",
    "exp": "2026-07-09",
    "in": 0,
    "out": 0,
    "opening": 0.97,
    "location": "F1D21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "TETRA HYDRO LINALOOL",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "4.1kg loose",
    "totalStock": 4.1,
    "batchNo": "32035547G0",
    "mfg": "2026-01-28",
    "exp": "2027-01-28",
    "in": 0,
    "out": 0,
    "opening": 4.1,
    "location": "F1D21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GERANIOL 98",
    "brand": "DRT",
    "packing": null,
    "article": null,
    "packingDetail": "4.9kg loose",
    "totalStock": 4.9,
    "batchNo": "L202502042",
    "mfg": "2025-02-25",
    "exp": "2027-02-25",
    "in": 0,
    "out": 0,
    "opening": 4.9,
    "location": "F1D21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GERANIOL 98",
    "brand": "DRT",
    "packing": null,
    "article": null,
    "packingDetail": "14.98kg loose",
    "totalStock": 14.98,
    "batchNo": "L202502042",
    "mfg": "2025-02-25",
    "exp": "2027-02-25",
    "in": 0,
    "out": 0,
    "opening": 14.98,
    "location": "F1D21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GERANIOL 98",
    "brand": "DRT",
    "packing": 30,
    "article": null,
    "packingDetail": "1×30kg",
    "totalStock": 30,
    "batchNo": "L202502042",
    "mfg": "2025-02-25",
    "exp": "2027-02-25",
    "in": 0,
    "out": 0,
    "opening": 30,
    "location": "F1D21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GERANIOL 98",
    "brand": "DRT",
    "packing": null,
    "article": null,
    "packingDetail": "1.9kg loose",
    "totalStock": 1.9,
    "batchNo": "L202502042",
    "mfg": "2025-02-25",
    "exp": "2027-02-25",
    "in": 0,
    "out": 0,
    "opening": 1.9,
    "location": "F1D21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GERANIOL 60",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "9.85kg loose",
    "totalStock": 9.85,
    "batchNo": "55368916K0",
    "mfg": "2025-06-26",
    "exp": "2027-06-26",
    "in": 0,
    "out": 0,
    "opening": 9.85,
    "location": "F1D21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GERANIOL 60",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "7.8kg loose",
    "totalStock": 7.8,
    "batchNo": "23916675L0",
    "mfg": "2025-02-27",
    "exp": "2027-02-27",
    "in": 0,
    "out": 0,
    "opening": 7.8,
    "location": "F1D21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GERANIOL EXTRA",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "0.8kg loose",
    "totalStock": 0.8,
    "batchNo": "892223036W0",
    "mfg": "2026-03-10",
    "exp": "2028-03-09",
    "in": 0,
    "out": 0,
    "opening": 0.8,
    "location": "F1D21",
    "reservation": null
  },
  {
    "tally": null,
    "material": "COUMARIN",
    "brand": "ETERNIS",
    "packing": null,
    "article": null,
    "packingDetail": "1.7kg loose",
    "totalStock": 1.7,
    "batchNo": "1104JD2036",
    "mfg": "2026-04-28",
    "exp": "2028-04-27",
    "in": 0,
    "out": 0,
    "opening": 1.7,
    "location": "F1D22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "COUMARIN",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "4.3kg loose",
    "totalStock": 4.3,
    "batchNo": "250411",
    "mfg": "2025-04-11",
    "exp": "2026-04-10",
    "in": 0,
    "out": 0,
    "opening": 4.3,
    "location": "F1D22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "COUMARIN",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "4.6kg loose",
    "totalStock": 4.6,
    "batchNo": "CP036-240617",
    "mfg": "2024-01-17",
    "exp": "2025-12-17",
    "in": 0,
    "out": 0,
    "opening": 4.6,
    "location": "F1D22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "COUMARIN",
    "brand": "CHINA",
    "packing": 50,
    "article": null,
    "packingDetail": "1×50kg",
    "totalStock": 50,
    "batchNo": "CP036-050805",
    "mfg": "2025-08-01",
    "exp": "2027-02-01",
    "in": 0,
    "out": 0,
    "opening": 50,
    "location": "F1D22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "MUSK XYLOL",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "15kg loose",
    "totalStock": 15,
    "batchNo": "2026032101",
    "mfg": "2026-03-21",
    "exp": "2028-03-20",
    "in": 0,
    "out": 0,
    "opening": 15,
    "location": "F1D18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "RASPBERRY KETONE",
    "brand": "NHU",
    "packing": null,
    "article": null,
    "packingDetail": "4.35kg loose",
    "totalStock": 4.35,
    "batchNo": "RK0826030116",
    "mfg": "2026-03-28",
    "exp": "2028-03-27",
    "in": 0,
    "out": 0,
    "opening": 4.35,
    "location": "F1D22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "METHYL OAKMOSS",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "0.06kg loose",
    "totalStock": 0.06,
    "batchNo": "MA24052701",
    "mfg": "2024-05-27",
    "exp": "2028-05-27",
    "in": 0,
    "out": 0,
    "opening": 0.06,
    "location": "F1D22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "VERAMOSS",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "3.7kg loose",
    "totalStock": 3.7,
    "batchNo": "260086",
    "mfg": "2026-06-02",
    "exp": "2028-06-01",
    "in": 0,
    "out": 0,
    "opening": 3.7,
    "location": "F1D22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "VERAMOSS",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "7kg loose",
    "totalStock": 7,
    "batchNo": "250076",
    "mfg": "2026-04-12",
    "exp": "2028-04-11",
    "in": 0,
    "out": 0,
    "opening": 7,
    "location": "F1D22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "VERAMOSS",
    "brand": "CHINA",
    "packing": 20,
    "article": null,
    "packingDetail": "5×20kg",
    "totalStock": 100,
    "batchNo": "260086",
    "mfg": "2026-06-02",
    "exp": "2028-06-01",
    "in": 0,
    "out": 0,
    "opening": 100,
    "location": "F1D22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "VERAMOSS",
    "brand": "CHINA",
    "packing": 20,
    "article": null,
    "packingDetail": "1×20kg",
    "totalStock": 20,
    "batchNo": "250076",
    "mfg": "2026-04-12",
    "exp": "2028-04-11",
    "in": 0,
    "out": 0,
    "opening": 20,
    "location": "F1D22",
    "reservation": null
  },
  {
    "tally": null,
    "material": "YARA YARA",
    "brand": "SHREE TULJA",
    "packing": null,
    "article": null,
    "packingDetail": "7kg loose",
    "totalStock": 7,
    "batchNo": "20260425",
    "mfg": "2026-04-01",
    "exp": "2027-03-01",
    "in": 0,
    "out": 0,
    "opening": 7,
    "location": "F1D23",
    "reservation": null
  },
  {
    "tally": null,
    "material": "YARA YARA",
    "brand": "GOGA",
    "packing": null,
    "article": null,
    "packingDetail": "2.9kg loose",
    "totalStock": 2.9,
    "batchNo": "20260425",
    "mfg": "2026-04-01",
    "exp": "2027-03-01",
    "in": 0,
    "out": 0,
    "opening": 2.9,
    "location": "F1D23",
    "reservation": null
  },
  {
    "tally": null,
    "material": "YARA YARA",
    "brand": "GOGA",
    "packing": null,
    "article": null,
    "packingDetail": "3kg loose",
    "totalStock": 3,
    "batchNo": "20260425",
    "mfg": "2026-04-01",
    "exp": "2027-03-01",
    "in": 0,
    "out": 0,
    "opening": 3,
    "location": "F1D23",
    "reservation": null
  },
  {
    "tally": null,
    "material": "YARA YARA",
    "brand": "GOGA",
    "packing": 25,
    "article": null,
    "packingDetail": "1×25kg",
    "totalStock": 25,
    "batchNo": "37",
    "mfg": "2023-10-01",
    "exp": "2025",
    "in": 0,
    "out": 0,
    "opening": 25,
    "location": "F1D23",
    "reservation": null
  },
  {
    "tally": null,
    "material": "YARA YARA",
    "brand": "GOGA",
    "packing": 25,
    "article": null,
    "packingDetail": "2×25kg",
    "totalStock": 50,
    "batchNo": "38",
    "mfg": "2024-12-01",
    "exp": "2025-11-01",
    "in": 0,
    "out": 0,
    "opening": 50,
    "location": "F1D23",
    "reservation": null
  },
  {
    "tally": null,
    "material": "YARA YARA",
    "brand": "SB",
    "packing": null,
    "article": null,
    "packingDetail": "3.1kg loose",
    "totalStock": 3.1,
    "batchNo": "2453/09/2024",
    "mfg": "2024-09-01",
    "exp": "2025-09-01",
    "in": 0,
    "out": 0,
    "opening": 3.1,
    "location": "F1D23",
    "reservation": null
  },
  {
    "tally": null,
    "material": "YARA YARA",
    "brand": "SB",
    "packing": null,
    "article": null,
    "packingDetail": "0.87kg loose",
    "totalStock": 0.87,
    "batchNo": "2453/09/2024",
    "mfg": "2024-09-01",
    "exp": "2025-09-01",
    "in": 0,
    "out": 0,
    "opening": 0.87,
    "location": "F1D23",
    "reservation": null
  },
  {
    "tally": null,
    "material": "YARA YARA",
    "brand": "KALPSUTRA",
    "packing": 25,
    "article": null,
    "packingDetail": "2×25kg",
    "totalStock": 50,
    "batchNo": "26/YY/VR#087",
    "mfg": "2026-02-20",
    "exp": "2028-02-19",
    "in": 0,
    "out": 0,
    "opening": 50,
    "location": "F1D23",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BETA IONONE",
    "brand": "BASF",
    "packing": 30,
    "article": null,
    "packingDetail": "3×30kg",
    "totalStock": 90,
    "batchNo": "95310888Q0",
    "mfg": "2025-06-17",
    "exp": "2027-06-17",
    "in": 0,
    "out": 0,
    "opening": 90,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BETA IONONE",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "19.95kg loose",
    "totalStock": 19.95,
    "batchNo": "95310888Q0",
    "mfg": "2025-06-17",
    "exp": "2027-06-17",
    "in": 0,
    "out": 0,
    "opening": 19.95,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DI ETHYL MALONATE",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "27kg loose",
    "totalStock": 27,
    "batchNo": "2025113001",
    "mfg": "2025-11-30",
    "exp": "2026-11-29",
    "in": 0,
    "out": 0,
    "opening": 27,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ETHYL CAPROATE",
    "brand": "FINE O CHEM",
    "packing": 30,
    "article": null,
    "packingDetail": "3×30kg",
    "totalStock": 90,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 90,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PTBCHA",
    "brand": "PRIVI",
    "packing": null,
    "article": null,
    "packingDetail": "2.1kg loose",
    "totalStock": 2.1,
    "batchNo": "0000360165",
    "mfg": "2025-06-18",
    "exp": "2027-06-08",
    "in": 0,
    "out": 0,
    "opening": 2.1,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PTBCHA",
    "brand": "MAC",
    "packing": null,
    "article": null,
    "packingDetail": "7.75kg loose",
    "totalStock": 7.75,
    "batchNo": "MI/OT/250501",
    "mfg": "2025-05-01",
    "exp": "2027-05-01",
    "in": 0,
    "out": 0,
    "opening": 7.75,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PTBCHA",
    "brand": "ETERNIS",
    "packing": null,
    "article": null,
    "packingDetail": "1.2kg loose",
    "totalStock": 1.2,
    "batchNo": "1003IK3001",
    "mfg": "2025-11-17",
    "exp": "2027-11-17",
    "in": 0,
    "out": 0,
    "opening": 1.2,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PTBCHA",
    "brand": "PRIVI",
    "packing": null,
    "article": null,
    "packingDetail": "3.7kg loose",
    "totalStock": 3.7,
    "batchNo": "0000390773",
    "mfg": "2025-09-05",
    "exp": "2027-08-26",
    "in": 0,
    "out": 0,
    "opening": 3.7,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PTBCHA",
    "brand": "MAC",
    "packing": null,
    "article": null,
    "packingDetail": "4.95kg loose",
    "totalStock": 4.95,
    "batchNo": "MI/OT/250501",
    "mfg": "2025-05-01",
    "exp": "2027-05-01",
    "in": 0,
    "out": 0,
    "opening": 4.95,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PTBCHA",
    "brand": "ETERNIS",
    "packing": 25,
    "article": null,
    "packingDetail": "4×25kg",
    "totalStock": 100,
    "batchNo": "1003JC2025",
    "mfg": "2026-03-23",
    "exp": "2028-03-22",
    "in": 0,
    "out": 0,
    "opening": 100,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PTBCHA",
    "brand": "ETERNIS",
    "packing": null,
    "article": null,
    "packingDetail": "1kg loose",
    "totalStock": 1,
    "batchNo": "1000IG4028",
    "mfg": "2025-07-26",
    "exp": "2027-07-26",
    "in": 0,
    "out": 0,
    "opening": 1,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PTBCHA",
    "brand": "ETERNIS",
    "packing": null,
    "article": null,
    "packingDetail": "7.9kg loose",
    "totalStock": 7.9,
    "batchNo": "1000IG4028",
    "mfg": "2025-07-26",
    "exp": "2027-07-26",
    "in": 0,
    "out": 0,
    "opening": 7.9,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PTBCHA",
    "brand": "MAC",
    "packing": null,
    "article": null,
    "packingDetail": "1kg loose",
    "totalStock": 1,
    "batchNo": "MI/OT/250501",
    "mfg": "2025-05-01",
    "exp": "2027-05-01",
    "in": 0,
    "out": 0,
    "opening": 1,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PTBCHA",
    "brand": "ETERNIS",
    "packing": null,
    "article": null,
    "packingDetail": "18.18kg loose",
    "totalStock": 18.18,
    "batchNo": "1000IL4004",
    "mfg": "2025-12-02",
    "exp": "2027-12-02",
    "in": 0,
    "out": 0,
    "opening": 18.18,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ETHYL CAPROATE",
    "brand": "UK",
    "packing": null,
    "article": null,
    "packingDetail": "0.68kg loose",
    "totalStock": 0.68,
    "batchNo": "007811",
    "mfg": "2024-06-12",
    "exp": "2025-06-11",
    "in": 0,
    "out": 0,
    "opening": 0.68,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GERANYL BUTYRATE - 92",
    "brand": "JAYSHREE",
    "packing": null,
    "article": null,
    "packingDetail": "10kg loose",
    "totalStock": 10,
    "batchNo": "LN060103",
    "mfg": "2025-01-03",
    "exp": "2027-01-02",
    "in": 0,
    "out": 0,
    "opening": 10,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GERANYL BUTYRATE - 92",
    "brand": "JAYSHREE",
    "packing": null,
    "article": null,
    "packingDetail": "6.35kg loose",
    "totalStock": 6.35,
    "batchNo": "2025013001R-265",
    "mfg": "2025-01-30",
    "exp": "2026-01-29",
    "in": 0,
    "out": 0,
    "opening": 6.35,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "FORALYN D",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "13.8kg loose",
    "totalStock": 13.8,
    "batchNo": "25120633",
    "mfg": "2025-12-01",
    "exp": "2026-12-01",
    "in": 0,
    "out": 0,
    "opening": 13.8,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "FORALYN D",
    "brand": "CHINA",
    "packing": 30,
    "article": null,
    "packingDetail": "1×30kg",
    "totalStock": 30,
    "batchNo": "25120633",
    "mfg": "2025-12-01",
    "exp": "2026-12-01",
    "in": 0,
    "out": 0,
    "opening": 30,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "FORALYN D",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "0.8kg loose",
    "totalStock": 0.8,
    "batchNo": "24060503",
    "mfg": "2024-06-01",
    "exp": "2026-06-01",
    "in": 0,
    "out": 0,
    "opening": 0.8,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PYRANOL",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "29.92kg loose",
    "totalStock": 29.92,
    "batchNo": "01973429U0",
    "mfg": "2026-02-11",
    "exp": "2028-02-11",
    "in": 0,
    "out": 0,
    "opening": 29.92,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PYRANOL",
    "brand": "BASF",
    "packing": 30,
    "article": null,
    "packingDetail": "2×30kg",
    "totalStock": 60,
    "batchNo": "01973429U0",
    "mfg": "2026-02-11",
    "exp": "2028-02-11",
    "in": 0,
    "out": 0,
    "opening": 60,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PYRANOL",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "0.4kg loose",
    "totalStock": 0.4,
    "batchNo": "13176009T0",
    "mfg": "2025-02-12",
    "exp": "2027-02-12",
    "in": 0,
    "out": 0,
    "opening": 0.4,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PYRANOL",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "0.4kg loose",
    "totalStock": 0.4,
    "batchNo": "92070909T0",
    "mfg": "2025-03-03",
    "exp": "2027-03-03",
    "in": 0,
    "out": 0,
    "opening": 0.4,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PYRANOL",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "3.28kg loose",
    "totalStock": 3.28,
    "batchNo": "14039624U0",
    "mfg": "2025-05-18",
    "exp": "2027-06-18",
    "in": 0,
    "out": 0,
    "opening": 3.28,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CAMPHOROIL",
    "brand": "ORIENTAL",
    "packing": null,
    "article": null,
    "packingDetail": "0.27kg loose",
    "totalStock": 0.27,
    "batchNo": "2024/AB0R037/001",
    "mfg": "2024-01-01",
    "exp": "2025-12-01",
    "in": 0,
    "out": 0,
    "opening": 0.27,
    "location": "F1D25",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ETHYL MALTOL",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "10kg loose",
    "totalStock": 10,
    "batchNo": "202512202",
    "mfg": "2025-12-20",
    "exp": "2027-12-19",
    "in": 0,
    "out": 0,
    "opening": 10,
    "location": "F1D26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ETHYL MALTOL",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "2.25kg loose",
    "totalStock": 2.25,
    "batchNo": "202601202",
    "mfg": "2026-01-20",
    "exp": "2028-01-19",
    "in": 0,
    "out": 0,
    "opening": 2.25,
    "location": "F1D26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ETHYL MALTOL",
    "brand": "O",
    "packing": null,
    "article": null,
    "packingDetail": "11.24kg loose",
    "totalStock": 11.24,
    "batchNo": "202510032",
    "mfg": "2025-10-03",
    "exp": "2027-10-02",
    "in": 0,
    "out": 0,
    "opening": 11.24,
    "location": "F1D26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ETHYL MALTOL",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "14.95kg loose",
    "totalStock": 14.95,
    "batchNo": "202601202",
    "mfg": "2026-01-20",
    "exp": "2028-01-19",
    "in": 0,
    "out": 0,
    "opening": 14.95,
    "location": "F1D26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "MUSK AMBERTTE",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "0.6kg loose",
    "totalStock": 0.6,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 0.6,
    "location": "F1D26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "MUSK AMBERTTE",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "0.2kg loose",
    "totalStock": 0.2,
    "batchNo": null,
    "mfg": "2025-04-01",
    "exp": "2027-04-01",
    "in": 0,
    "out": 0,
    "opening": 0.2,
    "location": "F1D26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ISO EUGENYL ACETATE",
    "brand": "GEM",
    "packing": null,
    "article": null,
    "packingDetail": "3.5kg loose",
    "totalStock": 3.5,
    "batchNo": "2410076",
    "mfg": "2024-10-25",
    "exp": "2026-10-24",
    "in": 0,
    "out": 0,
    "opening": 3.5,
    "location": "F1D26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "THYMOL CRYSTALS",
    "brand": "VDH",
    "packing": null,
    "article": null,
    "packingDetail": "8.6kg loose",
    "totalStock": 8.6,
    "batchNo": "VDH/TC/306/25-26",
    "mfg": "2025-06-11",
    "exp": "2028-06-11",
    "in": 0,
    "out": 0,
    "opening": 8.6,
    "location": "F1D26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "THYMOL CRYSTALS",
    "brand": "VDH",
    "packing": 25,
    "article": null,
    "packingDetail": "1×25kg",
    "totalStock": 25,
    "batchNo": "VDH/TC/102/25-26",
    "mfg": "2026-02-04",
    "exp": "2029-02-04",
    "in": 0,
    "out": 0,
    "opening": 25,
    "location": "F1D26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "MUSK KETONE",
    "brand": "S",
    "packing": null,
    "article": null,
    "packingDetail": "4.5kg loose",
    "totalStock": 4.5,
    "batchNo": "2025090420",
    "mfg": "2025-09-04",
    "exp": "2027-03-03",
    "in": 0,
    "out": 0,
    "opening": 4.5,
    "location": "F1D26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "MUSK KETONE",
    "brand": "S",
    "packing": null,
    "article": null,
    "packingDetail": "5kg loose",
    "totalStock": 5,
    "batchNo": "2026010801",
    "mfg": "2026-01-08",
    "exp": "2028-01-07",
    "in": 0,
    "out": 0,
    "opening": 5,
    "location": "F1D26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "TINOGARD TT",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "5kg loose",
    "totalStock": 5,
    "batchNo": "0029545443",
    "mfg": "2025-07-26",
    "exp": "2030-06-30",
    "in": 0,
    "out": 0,
    "opening": 5,
    "location": "F1D26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "TINOGARD TT",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "2×40kg loose",
    "totalStock": 80,
    "batchNo": "0029856377",
    "mfg": "2025-07-26",
    "exp": "2030-06-30",
    "in": 0,
    "out": 0,
    "opening": 80,
    "location": "F1D26",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ISO AMYL ACETATE",
    "brand": "SG",
    "packing": null,
    "article": null,
    "packingDetail": "15.5kg loose",
    "totalStock": 15.5,
    "batchNo": "IAAC/050037/25-26",
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 15.5,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ISO AMYL ACETATE",
    "brand": "JY",
    "packing": null,
    "article": null,
    "packingDetail": "23.53kg loose",
    "totalStock": 23.53,
    "batchNo": "2022022401R-549",
    "mfg": "2022-02-24",
    "exp": "2024-02-23",
    "in": 0,
    "out": 0,
    "opening": 23.53,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ISO AMYL ACETATE",
    "brand": "SYNERGIN",
    "packing": null,
    "article": null,
    "packingDetail": "25kg loose",
    "totalStock": 25,
    "batchNo": "LN561245",
    "mfg": "2025-04-01",
    "exp": "2027-05-01",
    "in": 0,
    "out": 0,
    "opening": 25,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ISO AMYL ACETATE",
    "brand": "SG",
    "packing": null,
    "article": null,
    "packingDetail": "12kg loose",
    "totalStock": 12,
    "batchNo": "IAAC/050042/25-26",
    "mfg": "2026-01-01",
    "exp": "2028-01-01",
    "in": 0,
    "out": 0,
    "opening": 12,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ISO AMYL ACETATE",
    "brand": "SG",
    "packing": null,
    "article": null,
    "packingDetail": "21.2kg loose",
    "totalStock": 21.2,
    "batchNo": "IAAC/050018/25-26",
    "mfg": "2025-07-01",
    "exp": "2027-07-01",
    "in": 0,
    "out": 0,
    "opening": 21.2,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ISO AMYL ACETATE",
    "brand": "SG",
    "packing": null,
    "article": null,
    "packingDetail": "5kg loose",
    "totalStock": 5,
    "batchNo": "IAAC/050018/25-26",
    "mfg": "2025-07-01",
    "exp": "2027-07-01",
    "in": 0,
    "out": 0,
    "opening": 5,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ISO AMYL ACETATE",
    "brand": "SG",
    "packing": null,
    "article": null,
    "packingDetail": "0.4kg loose",
    "totalStock": 0.4,
    "batchNo": "IAAC/050017/23-24",
    "mfg": "2023-04-01",
    "exp": "2025-04-01",
    "in": 0,
    "out": 0,
    "opening": 0.4,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ISO AMYL ACETATE",
    "brand": "SYNERGIN",
    "packing": null,
    "article": null,
    "packingDetail": "0.78kg loose",
    "totalStock": 0.78,
    "batchNo": "2024004",
    "mfg": "2024-04-01",
    "exp": "2026-04-01",
    "in": 0,
    "out": 0,
    "opening": 0.78,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ISO AMYL ACETATE",
    "brand": "SYNERGIN",
    "packing": null,
    "article": null,
    "packingDetail": "2.8kg loose",
    "totalStock": 2.8,
    "batchNo": "2024004",
    "mfg": "2024-04-01",
    "exp": "2026-04-01",
    "in": 0,
    "out": 0,
    "opening": 2.8,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PHENYL PROPYL ALCOHOL",
    "brand": "HARMONY",
    "packing": null,
    "article": null,
    "packingDetail": "1.5kg loose",
    "totalStock": 1.5,
    "batchNo": "24070005",
    "mfg": "2024-07-01",
    "exp": "2025-06-01",
    "in": 0,
    "out": 0,
    "opening": 1.5,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ALPHA PINENE",
    "brand": "VIJAY",
    "packing": null,
    "article": null,
    "packingDetail": "0.3kg loose",
    "totalStock": 0.3,
    "batchNo": "9539/24-25",
    "mfg": "2024-07-19",
    "exp": "2027-07-12",
    "in": 0,
    "out": 0,
    "opening": 0.3,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ALPHA PINENE",
    "brand": "VIJAY",
    "packing": null,
    "article": null,
    "packingDetail": "0.46kg loose",
    "totalStock": 0.46,
    "batchNo": "I/NOV/24/ALPHA PINENE",
    "mfg": "2024-11-01",
    "exp": "2026-10-01",
    "in": 0,
    "out": 0,
    "opening": 0.46,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "INTRALDEHYDE C-11 ISO 30 %",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "3.55kg loose",
    "totalStock": 3.55,
    "batchNo": "77660/41/67",
    "mfg": "2025-03-20",
    "exp": "2026-03-19",
    "in": 0,
    "out": 0,
    "opening": 3.55,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "INTRALDEHYDE C-11 ISO 50 %",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "13.8kg loose",
    "totalStock": 13.8,
    "batchNo": "LN060159",
    "mfg": "2026-03-02",
    "exp": "2027-03-01",
    "in": 0,
    "out": 0,
    "opening": 13.8,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PHENYL PROPYL ALCOHOL",
    "brand": "HARMONY",
    "packing": null,
    "article": null,
    "packingDetail": "3.6kg loose",
    "totalStock": 3.6,
    "batchNo": "PPA25080012",
    "mfg": "2025-08-28",
    "exp": "2026-08-17",
    "in": 0,
    "out": 0,
    "opening": 3.6,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PHENYL PROPYL ALCOHOL",
    "brand": "ASHAPURA (OLD)",
    "packing": null,
    "article": null,
    "packingDetail": "14kg loose",
    "totalStock": 14,
    "batchNo": "2018092101R-623",
    "mfg": "2025-08-28",
    "exp": "2026-08-17",
    "in": 0,
    "out": 0,
    "opening": 14,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CITRONELLA OIL",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "18.9kg loose",
    "totalStock": 18.9,
    "batchNo": "0102025",
    "mfg": "2025-12-01",
    "exp": "2028-12-01",
    "in": 0,
    "out": 0,
    "opening": 18.9,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PARAANISYL ACETATE",
    "brand": "JAYSHREE",
    "packing": null,
    "article": null,
    "packingDetail": "9.2kg loose",
    "totalStock": 9.2,
    "batchNo": "2025102901R-261",
    "mfg": "2025-10-29",
    "exp": "2026-10-28",
    "in": 0,
    "out": 0,
    "opening": 9.2,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BENZYL PHENYL ACETATE",
    "brand": "JAYSHREE",
    "packing": null,
    "article": null,
    "packingDetail": "13.8kg loose",
    "totalStock": 13.8,
    "batchNo": "LN060239",
    "mfg": "2026-06-20",
    "exp": "2027-06-19",
    "in": 0,
    "out": 0,
    "opening": 13.8,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "MYRAC ALDEHYDE",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "6.9kg loose",
    "totalStock": 6.9,
    "batchNo": "LN060170",
    "mfg": "2026-03-06",
    "exp": "2027-03-05",
    "in": 0,
    "out": 0,
    "opening": 6.9,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "COMP. HAV-A",
    "brand": null,
    "packing": 25,
    "article": null,
    "packingDetail": "1×25kg",
    "totalStock": 25,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 25,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BASE 701",
    "brand": null,
    "packing": 25,
    "article": null,
    "packingDetail": "7×25kg",
    "totalStock": 175,
    "batchNo": "GX3400",
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 175,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BASE 701",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "24.9kg loose",
    "totalStock": 24.9,
    "batchNo": "GX3400",
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 24.9,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "LAVENDIN STD",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "9kg loose",
    "totalStock": 9,
    "batchNo": null,
    "mfg": "2024-06-01",
    "exp": "2026-06-01",
    "in": 0,
    "out": 0,
    "opening": 9,
    "location": "F1D29",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PAA FLAKES",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "1.7kg loose",
    "totalStock": 1.7,
    "batchNo": "J2/1",
    "mfg": "2026-01-09",
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 1.7,
    "location": "F1D31",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PAA FLAKES",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "0.8kg loose",
    "totalStock": 0.8,
    "batchNo": "J2/1",
    "mfg": "2026-01-09",
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 0.8,
    "location": "F1D31",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PAA FLAKES",
    "brand": null,
    "packing": 25,
    "article": null,
    "packingDetail": "3×25kg",
    "totalStock": 75,
    "batchNo": "J4/7",
    "mfg": "2026-07-17",
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 75,
    "location": "F1D31",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PAA FLAKES",
    "brand": null,
    "packing": 25,
    "article": null,
    "packingDetail": "2×25kg",
    "totalStock": 50,
    "batchNo": "J8/3",
    "mfg": "2026-03-26",
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 50,
    "location": "F1D31",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PAA FLAKES",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "19.5kg loose",
    "totalStock": 19.5,
    "batchNo": "J4/7",
    "mfg": "2026-07-17",
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 19.5,
    "location": "F1D31",
    "reservation": null
  },
  {
    "tally": null,
    "material": "METHYL IONONE 70",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "3.65kg loose",
    "totalStock": 3.65,
    "batchNo": "65970336W0",
    "mfg": "2025-06-03",
    "exp": "2027-06-03",
    "in": 0,
    "out": 0,
    "opening": 3.65,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "METHYL IONONE 70",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "16.8kg loose",
    "totalStock": 16.8,
    "batchNo": "60554124U0",
    "mfg": "2026-01-26",
    "exp": "2028-01-26",
    "in": 0,
    "out": 0,
    "opening": 16.8,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "METHYL IONONE 70",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "12.64kg loose",
    "totalStock": 12.64,
    "batchNo": "60554124U0",
    "mfg": "2026-01-26",
    "exp": "2028-01-26",
    "in": 0,
    "out": 0,
    "opening": 12.64,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "METHYL IONONE 70",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "0.26kg loose",
    "totalStock": 0.26,
    "batchNo": "60554124U0",
    "mfg": "2026-01-26",
    "exp": "2028-01-26",
    "in": 0,
    "out": 0,
    "opening": 0.26,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "HEXYL CINNAMIC ALDEHYDE",
    "brand": "KALAMA",
    "packing": null,
    "article": null,
    "packingDetail": "4.5kg loose",
    "totalStock": 4.5,
    "batchNo": "KAHCT43308",
    "mfg": "2024-03-29",
    "exp": "2025-03-29",
    "in": 0,
    "out": 0,
    "opening": 4.5,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "HYDROXY CITRONELLAL",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "4.62kg loose",
    "totalStock": 4.62,
    "batchNo": "34384288Q0",
    "mfg": "2025-11-13",
    "exp": "2027-11-13",
    "in": 0,
    "out": 0,
    "opening": 4.62,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "HYDROXY CITRONELLAL",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "17.42kg loose",
    "totalStock": 17.42,
    "batchNo": "87977077L0",
    "mfg": "2026-03-06",
    "exp": "2028-03-05",
    "in": 0,
    "out": 0,
    "opening": 17.42,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DHM",
    "brand": "PRIVI",
    "packing": null,
    "article": null,
    "packingDetail": "14.9kg loose",
    "totalStock": 14.9,
    "batchNo": "0000510653",
    "mfg": "2026-06-29",
    "exp": "2028-06-18",
    "in": 0,
    "out": 0,
    "opening": 14.9,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DOWANOL DPM",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "3×30kg loose",
    "totalStock": 90,
    "batchNo": "20260605",
    "mfg": "2026-06-05",
    "exp": "2027-06-05",
    "in": 0,
    "out": 0,
    "opening": 90,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DOWANOL DPM",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "24.8kg loose",
    "totalStock": 24.8,
    "batchNo": "20260605",
    "mfg": "2026-06-05",
    "exp": "2027-06-05",
    "in": 0,
    "out": 0,
    "opening": 24.8,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CINNAMIC ALDEHYDE",
    "brand": "LX",
    "packing": null,
    "article": null,
    "packingDetail": "1.55kg loose",
    "totalStock": 1.55,
    "batchNo": "24CAL015D",
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 1.55,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CINNAMIC ALDEHYDE",
    "brand": "LX",
    "packing": null,
    "article": null,
    "packingDetail": "5.35kg loose",
    "totalStock": 5.35,
    "batchNo": "24CAL015D",
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 5.35,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CINNAMIC ALDEHYDE",
    "brand": "H",
    "packing": null,
    "article": null,
    "packingDetail": "9.7kg loose",
    "totalStock": 9.7,
    "batchNo": "25100073",
    "mfg": "2025-10-30",
    "exp": "2026-10-29",
    "in": 0,
    "out": 0,
    "opening": 9.7,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CINNAMIC ALDEHYDE",
    "brand": "H",
    "packing": 35,
    "article": null,
    "packingDetail": "4×35kg",
    "totalStock": 70,
    "batchNo": "25100073",
    "mfg": "2025-10-30",
    "exp": "2026-10-29",
    "in": 0,
    "out": 0,
    "opening": 70,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CINNAMIC ALDEHYDE",
    "brand": "LX",
    "packing": null,
    "article": null,
    "packingDetail": "1kg loose",
    "totalStock": 1,
    "batchNo": "24CAL015D",
    "mfg": "2025-10-30",
    "exp": "2026-10-29",
    "in": 0,
    "out": 0,
    "opening": 1,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CINNAMIC ALDEHYDE",
    "brand": "LX",
    "packing": null,
    "article": null,
    "packingDetail": "23.98kg loose",
    "totalStock": 23.98,
    "batchNo": "LN060171",
    "mfg": "2026-03-28",
    "exp": "2027-03-27",
    "in": 0,
    "out": 0,
    "opening": 23.98,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CITRONELLYL PROPIONATE",
    "brand": "JAYSHREE",
    "packing": null,
    "article": null,
    "packingDetail": "10kg loose",
    "totalStock": 10,
    "batchNo": "2025070401R-057",
    "mfg": "2025-07-04",
    "exp": "2026-07-03",
    "in": 0,
    "out": 0,
    "opening": 10,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CITRONELLYL PROPIONATE",
    "brand": "JAYSHREE",
    "packing": 30,
    "article": null,
    "packingDetail": "1×30kg",
    "totalStock": 30,
    "batchNo": "2025070401R-057",
    "mfg": "2025-07-04",
    "exp": "2026-07-03",
    "in": 0,
    "out": 0,
    "opening": 30,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "HELIONAL",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "0.64kg loose",
    "totalStock": 0.64,
    "batchNo": "202505001",
    "mfg": "2025-05-10",
    "exp": "2027-05-09",
    "in": 0,
    "out": 0,
    "opening": 0.64,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "HELIONAL",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "14.99kg loose",
    "totalStock": 14.99,
    "batchNo": "20250822",
    "mfg": "2025-08-22",
    "exp": "2027-08-21",
    "in": 0,
    "out": 0,
    "opening": 14.99,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "HELIONAL",
    "brand": "CHINA",
    "packing": 30,
    "article": null,
    "packingDetail": "2×30kg",
    "totalStock": 60,
    "batchNo": "202602006",
    "mfg": "2026-02-05",
    "exp": "2028-02-04",
    "in": 0,
    "out": 0,
    "opening": 60,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "HELIONAL",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "29.93kg loose",
    "totalStock": 29.93,
    "batchNo": "202602006",
    "mfg": "2026-02-05",
    "exp": "2028-02-04",
    "in": 0,
    "out": 0,
    "opening": 29.93,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "HELIONAL",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "23.98kg loose",
    "totalStock": 23.98,
    "batchNo": "20250822",
    "mfg": "2025-08-22",
    "exp": "2027-08-21",
    "in": 0,
    "out": 0,
    "opening": 23.98,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PHENOXY ETHYL ISO BUTYRATE",
    "brand": "J",
    "packing": null,
    "article": null,
    "packingDetail": "19.2kg loose",
    "totalStock": 19.2,
    "batchNo": "2025012501R-213",
    "mfg": "2025-01-25",
    "exp": "2026-01-24",
    "in": 0,
    "out": 0,
    "opening": 19.2,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BENZYL SALICYLATE",
    "brand": "E",
    "packing": null,
    "article": null,
    "packingDetail": "18.8kg loose",
    "totalStock": 18.8,
    "batchNo": "1006II7005",
    "mfg": "2025-09-09",
    "exp": "2026-09-09",
    "in": 0,
    "out": 0,
    "opening": 18.8,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DPG",
    "brand": "M",
    "packing": null,
    "article": null,
    "packingDetail": "5.99kg loose",
    "totalStock": 5.99,
    "batchNo": "DPG-FRG/2023-24/1008",
    "mfg": "2023-05-01",
    "exp": "2025-04-01",
    "in": 0,
    "out": 0,
    "opening": 5.99,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DPG",
    "brand": "SK",
    "packing": null,
    "article": null,
    "packingDetail": "5kg loose",
    "totalStock": 5,
    "batchNo": "KI0311DF1A",
    "mfg": "2025-10-31",
    "exp": "2027-10-30",
    "in": 0,
    "out": 0,
    "opening": 5,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DPG",
    "brand": "SK",
    "packing": null,
    "article": null,
    "packingDetail": "9.98kg loose",
    "totalStock": 9.98,
    "batchNo": "KI0311DF1A",
    "mfg": "2025-10-31",
    "exp": "2027-10-30",
    "in": 0,
    "out": 0,
    "opening": 9.98,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DPG",
    "brand": "SK",
    "packing": null,
    "article": null,
    "packingDetail": "8.54kg loose",
    "totalStock": 8.54,
    "batchNo": "KIB101DF1A",
    "mfg": "2025-12-10",
    "exp": "2027-12-09",
    "in": 0,
    "out": 0,
    "opening": 8.54,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DPG",
    "brand": "SK",
    "packing": 30,
    "article": null,
    "packingDetail": "1×30kg",
    "totalStock": 30,
    "batchNo": "KI0311DF1A",
    "mfg": "2025-10-31",
    "exp": "2027-10-30",
    "in": 0,
    "out": 0,
    "opening": 30,
    "location": "F1C9",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DPG",
    "brand": "SK",
    "packing": null,
    "article": null,
    "packingDetail": "20kg loose",
    "totalStock": 20,
    "batchNo": "KI0311DF1A",
    "mfg": "2025-10-31",
    "exp": "2027-10-30",
    "in": 0,
    "out": 0,
    "opening": 20,
    "location": "F1C9",
    "reservation": null
  }
];

export const NEW_LOCATIONS = [
  "F1C9",
  "F1D18",
  "F1D19",
  "F1D21",
  "F1D22",
  "F1D23",
  "F1D25",
  "F1D26",
  "F1D29",
  "F1D31"
];
