// Holds only the newest CSV batch to import — replace the contents of NEW_STOCK_ITEMS
// (and NEW_LOCATIONS, if the batch introduces bin codes not already in the DB) each time
// a new stock sheet comes in, then run `npm run import-stock`.
// Current batch: STOCK LOCATION 12TH AUG & 14TH AUG.csv (102 items).
export const NEW_STOCK_ITEMS = [
  {
    "tally": null,
    "material": "STRAWBERRY ALD. (C-16)",
    "brand": "AQUILA",
    "packing": 30,
    "article": null,
    "packingDetail": "2×30kg",
    "totalStock": 60,
    "batchNo": "023/067/03/26",
    "mfg": "2026-03-23",
    "exp": "2027-03-22",
    "in": 0,
    "out": 0,
    "opening": 60,
    "location": "F1D13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "STRAWBERRY ALD. (C-16)",
    "brand": "HARMONY",
    "packing": null,
    "article": null,
    "packingDetail": "8.95kg loose",
    "totalStock": 8.95,
    "batchNo": "25070013",
    "mfg": "2025-07-18",
    "exp": "2026-07-17",
    "in": 0,
    "out": 0,
    "opening": 8.95,
    "location": "F1D13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "STRAWBERRY ALD. (C-16)",
    "brand": "AQUILA",
    "packing": null,
    "article": null,
    "packingDetail": "6kg loose",
    "totalStock": 6,
    "batchNo": "023/027/11/25",
    "mfg": "2025-11-11",
    "exp": "2026-11-10",
    "in": 0,
    "out": 0,
    "opening": 6,
    "location": "F1D13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "STRAWBERRY ALD. (C-16)",
    "brand": "PRASAD",
    "packing": 30,
    "article": null,
    "packingDetail": "4×30kg",
    "totalStock": 120,
    "batchNo": "C16202627012",
    "mfg": "2025-11-11",
    "exp": "2026-11-10",
    "in": 0,
    "out": 0,
    "opening": 120,
    "location": "F1D13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "STRAWBERRY ALD. (C-16)",
    "brand": "PRASAD",
    "packing": null,
    "article": null,
    "packingDetail": "1.3kg loose",
    "totalStock": 1.3,
    "batchNo": "C16202526004",
    "mfg": "2025-11-11",
    "exp": "2026-11-10",
    "in": 0,
    "out": 0,
    "opening": 1.3,
    "location": "F1D13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "STRAWBERRY ALD. (C-16)",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "0.5kg loose",
    "totalStock": 0.5,
    "batchNo": "240318",
    "mfg": "2024-03-18",
    "exp": "2026-03-17",
    "in": 0,
    "out": 0,
    "opening": 0.5,
    "location": "F1D13",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AMBROXIDE/AMBROXAN",
    "brand": "CHINA",
    "packing": 25,
    "article": null,
    "packingDetail": "6×25kg",
    "totalStock": 150,
    "batchNo": "AB-260706",
    "mfg": "2026-07-28",
    "exp": "2028-07-28",
    "in": 0,
    "out": 0,
    "opening": 150,
    "location": "F1D14",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AMBROXIDE/AMBROXAN",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "20kg loose",
    "totalStock": 20,
    "batchNo": "AB-260601",
    "mfg": "2026-06-01",
    "exp": "2028-05-31",
    "in": 0,
    "out": 0,
    "opening": 20,
    "location": "F1D14",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AMBROXIDE/AMBROXAN",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "6×0.5kg loose",
    "totalStock": 3,
    "batchNo": "260501",
    "mfg": "2026-05-01",
    "exp": "2028-05-01",
    "in": 0,
    "out": 0,
    "opening": 3,
    "location": "F1D14",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AMBROXIDE/AMBROXAN",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "0.179kg loose",
    "totalStock": 0.179,
    "batchNo": "260501",
    "mfg": "2026-05-01",
    "exp": "2028-05-01",
    "in": 0,
    "out": 0,
    "opening": 0.179,
    "location": "F1D14",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AMBROFIX",
    "brand": "GIVAUDAN",
    "packing": 25,
    "article": null,
    "packingDetail": "1×25kg",
    "totalStock": 25,
    "batchNo": "VE00883633",
    "mfg": "2025-03-30",
    "exp": "2028-03-19",
    "in": 0,
    "out": 0,
    "opening": 25,
    "location": "F1D14",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AMBROFIX",
    "brand": "GIVAUDAN",
    "packing": null,
    "article": null,
    "packingDetail": "0.07kg loose",
    "totalStock": 0.07,
    "batchNo": "VE00883633",
    "mfg": "2025-03-30",
    "exp": "2028-03-19",
    "in": 0,
    "out": 0,
    "opening": 0.07,
    "location": "F1D14",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AMBROFIX",
    "brand": "GIVAUDAN",
    "packing": null,
    "article": null,
    "packingDetail": "0.8kg loose",
    "totalStock": 0.8,
    "batchNo": "VE00804377",
    "mfg": "2022-12-08",
    "exp": "2025-02-25",
    "in": 0,
    "out": 0,
    "opening": 0.8,
    "location": "F1D14",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AMBROZANE/ AMBROXAN",
    "brand": "ORIENTAL",
    "packing": null,
    "article": null,
    "packingDetail": "0.085kg loose",
    "totalStock": 0.085,
    "batchNo": "V25F005129",
    "mfg": "2025-06-08",
    "exp": "2026-06-07",
    "in": 0,
    "out": 0,
    "opening": 0.085,
    "location": "F1D14",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AMBROZANE/ AMBROXAN",
    "brand": "ORIENTAL",
    "packing": null,
    "article": null,
    "packingDetail": "0.075kg loose",
    "totalStock": 0.075,
    "batchNo": "V24F003789",
    "mfg": "2024-10-19",
    "exp": "2025-10-18",
    "in": 0,
    "out": 0,
    "opening": 0.075,
    "location": "F1D14",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AMBROZANE/ AMBROXAN",
    "brand": "ORIENTAL",
    "packing": 20,
    "article": null,
    "packingDetail": "1×20kg",
    "totalStock": 20,
    "batchNo": "V26F007218",
    "mfg": "2026-06-22",
    "exp": "2027-06-21",
    "in": 0,
    "out": 0,
    "opening": 20,
    "location": "F1D14",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AMBROZANE/ AMBROXAN",
    "brand": "ORIENTAL",
    "packing": null,
    "article": null,
    "packingDetail": "19kg loose",
    "totalStock": 19,
    "batchNo": "V26F007218",
    "mfg": "2026-06-22",
    "exp": "2027-06-21",
    "in": 0,
    "out": 0,
    "opening": 19,
    "location": "F1D14",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AMBER FLEUR",
    "brand": "PRIVI",
    "packing": null,
    "article": null,
    "packingDetail": "2.8kg loose",
    "totalStock": 2.8,
    "batchNo": "0000473470",
    "mfg": "2026-03-23",
    "exp": "2028-03-12",
    "in": 0,
    "out": 0,
    "opening": 2.8,
    "location": "F1B5",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AMBROFIX/ AMBROXAN",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "0.01kg loose",
    "totalStock": 0.01,
    "batchNo": "AB/AM/007/0525",
    "mfg": "2025-05-01",
    "exp": "2027-04-01",
    "in": 0,
    "out": 0,
    "opening": 0.01,
    "location": "F1D14",
    "reservation": null
  },
  {
    "tally": null,
    "material": "MALTOL",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "3kg loose",
    "totalStock": 3,
    "batchNo": "202309211",
    "mfg": "2023-09-21",
    "exp": "2025-09-20",
    "in": 0,
    "out": 0,
    "opening": 3,
    "location": "F1D14",
    "reservation": null
  },
  {
    "tally": null,
    "material": "MALTOL",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "14.4kg loose",
    "totalStock": 14.4,
    "batchNo": "202508111",
    "mfg": "2025-08-11",
    "exp": "2027-08-01",
    "in": 0,
    "out": 0,
    "opening": 14.4,
    "location": "F1D14",
    "reservation": null
  },
  {
    "tally": null,
    "material": "L MENTHOL FLAKES PHARMA",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "14kg loose",
    "totalStock": 14,
    "batchNo": "27964547G0",
    "mfg": "2024-08-13",
    "exp": "2029-08-12",
    "in": 0,
    "out": 0,
    "opening": 14,
    "location": "F1D15",
    "reservation": null
  },
  {
    "tally": null,
    "material": "MENTHOL CRYSTAL",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "17kg loose",
    "totalStock": 17,
    "batchNo": "49",
    "mfg": "2026-04-01",
    "exp": "2028-05-01",
    "in": 0,
    "out": 0,
    "opening": 17,
    "location": "F1D15",
    "reservation": null
  },
  {
    "tally": null,
    "material": "DIMETHYL HYDROQUINONE",
    "brand": "CAMLIN",
    "packing": null,
    "article": null,
    "packingDetail": "0.86kg loose",
    "totalStock": 0.86,
    "batchNo": "ADM022J001",
    "mfg": "2022-10-01",
    "exp": "2024-09-01",
    "in": 0,
    "out": 0,
    "opening": 0.86,
    "location": "F1D15",
    "reservation": null
  },
  {
    "tally": null,
    "material": "P.C.P.A",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "24kg loose",
    "totalStock": 24,
    "batchNo": "5/5",
    "mfg": "2026-05-29",
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 24,
    "location": "F1D15",
    "reservation": null
  },
  {
    "tally": null,
    "material": "MEGASANTOL",
    "brand": "HAC",
    "packing": null,
    "article": null,
    "packingDetail": "2.18kg loose",
    "totalStock": 2.18,
    "batchNo": "0100190348",
    "mfg": "2025-05-06",
    "exp": "2026-11-06",
    "in": 0,
    "out": 0,
    "opening": 2.18,
    "location": "F1D17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "MEGASANTOL",
    "brand": "HAC",
    "packing": null,
    "article": null,
    "packingDetail": "11.65kg loose",
    "totalStock": 11.65,
    "batchNo": "LN060195",
    "mfg": "2026-04-18",
    "exp": "2027-04-18",
    "in": 0,
    "out": 0,
    "opening": 11.65,
    "location": "F1D17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "RHODINOL",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "3.1kg loose",
    "totalStock": 3.1,
    "batchNo": "002601",
    "mfg": "2026-01-01",
    "exp": "2027-01-01",
    "in": 0,
    "out": 0,
    "opening": 3.1,
    "location": "F1D17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "RHODINOL",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "0.8kg loose",
    "totalStock": 0.8,
    "batchNo": "002211",
    "mfg": "2022-11-01",
    "exp": "2027-10-01",
    "in": 0,
    "out": 0,
    "opening": 0.8,
    "location": "F1D17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "RHODINOL",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "25kg loose",
    "totalStock": 25,
    "batchNo": "002608",
    "mfg": "2026-08-01",
    "exp": "2028-07-01",
    "in": 0,
    "out": 0,
    "opening": 25,
    "location": "F1D17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "FRUCTON",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "1.27kg loose",
    "totalStock": 1.27,
    "batchNo": "240516",
    "mfg": "2024-05-01",
    "exp": "2026-05-01",
    "in": 0,
    "out": 0,
    "opening": 1.27,
    "location": "F1D17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "FRUCTON",
    "brand": "ARPAN",
    "packing": null,
    "article": null,
    "packingDetail": "0.1kg loose",
    "totalStock": 0.1,
    "batchNo": "202403261",
    "mfg": "2024-03-01",
    "exp": "2026-03-01",
    "in": 0,
    "out": 0,
    "opening": 0.1,
    "location": "F1D17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "FRUCTON",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "14.9kg loose",
    "totalStock": 14.9,
    "batchNo": "03017Y2A03",
    "mfg": "2025-04-24",
    "exp": "2027-04-23",
    "in": 0,
    "out": 0,
    "opening": 14.9,
    "location": "F1D17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "FRUCTON",
    "brand": "CHINA",
    "packing": 30,
    "article": null,
    "packingDetail": "3×30kg",
    "totalStock": 90,
    "batchNo": "03017Y2A03",
    "mfg": "2025-04-24",
    "exp": "2027-04-23",
    "in": 0,
    "out": 0,
    "opening": 90,
    "location": "F1D17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "APPLE KETAL",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "0.95kg loose",
    "totalStock": 0.95,
    "batchNo": "6413-10-1",
    "mfg": "2024-02-01",
    "exp": "2026-02-01",
    "in": 0,
    "out": 0,
    "opening": 0.95,
    "location": "F1D17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "STYRALLYL ACETATE",
    "brand": "HARMONY",
    "packing": 30,
    "article": null,
    "packingDetail": "6×30kg",
    "totalStock": 180,
    "batchNo": "26020062",
    "mfg": "2026-02-10",
    "exp": "2027-02-09",
    "in": 0,
    "out": 0,
    "opening": 180,
    "location": "F1D17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "STYRALLYL ACETATE",
    "brand": "HARMONY",
    "packing": null,
    "article": null,
    "packingDetail": "5.1kg loose",
    "totalStock": 5.1,
    "batchNo": "26020062",
    "mfg": "2026-02-10",
    "exp": "2027-02-09",
    "in": 0,
    "out": 0,
    "opening": 5.1,
    "location": "F1D17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "STYRALLYL ACETATE",
    "brand": "ESTERN",
    "packing": null,
    "article": null,
    "packingDetail": "0.8kg loose",
    "totalStock": 0.8,
    "batchNo": "1002II1006",
    "mfg": "2025-09-16",
    "exp": "2027-09-16",
    "in": 0,
    "out": 0,
    "opening": 0.8,
    "location": "F1D17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ALLYL CYCLO HEXYL PROPINATE",
    "brand": "HAC",
    "packing": null,
    "article": null,
    "packingDetail": "16.65kg loose",
    "totalStock": 16.65,
    "batchNo": "0100190904",
    "mfg": "2025-07-28",
    "exp": "2028-07-28",
    "in": 0,
    "out": 0,
    "opening": 16.65,
    "location": "F1D17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "MUSK XYLOL",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "25kg loose",
    "totalStock": 25,
    "batchNo": "2026032101",
    "mfg": "2026-03-21",
    "exp": "2028-03-20",
    "in": 0,
    "out": 0,
    "opening": 25,
    "location": "F1D18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "MUSK XYLOL",
    "brand": "CHINA",
    "packing": 25,
    "article": null,
    "packingDetail": "4×25kg",
    "totalStock": 100,
    "batchNo": "2026032101",
    "mfg": "2026-03-21",
    "exp": "2028-03-20",
    "in": 0,
    "out": 0,
    "opening": 100,
    "location": "F1D18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "MUSK XYLOL",
    "brand": "ASHAPURA",
    "packing": null,
    "article": null,
    "packingDetail": "7.8kg loose",
    "totalStock": 7.8,
    "batchNo": "37603",
    "mfg": "2025-11-20",
    "exp": "2027-11-19",
    "in": 0,
    "out": 0,
    "opening": 7.8,
    "location": "F1D18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "MUSK XYLOL",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "5.8kg loose",
    "totalStock": 5.8,
    "batchNo": "2025071611",
    "mfg": "2025-07-16",
    "exp": "2027-01-15",
    "in": 0,
    "out": 0,
    "opening": 5.8,
    "location": "F1D18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "MUSK XYLOL",
    "brand": "MASCHMIEJER",
    "packing": null,
    "article": null,
    "packingDetail": "3kg loose",
    "totalStock": 3,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 3,
    "location": "F1D18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "MUSK XYLOL",
    "brand": "MASCHMIEJER",
    "packing": null,
    "article": null,
    "packingDetail": "1.8kg loose",
    "totalStock": 1.8,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 1.8,
    "location": "F1D18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "MUSK XYLOL",
    "brand": "MASCHMIEJER",
    "packing": 5,
    "article": null,
    "packingDetail": "1×5kg",
    "totalStock": 5,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 5,
    "location": "F1D18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "TONALIDE",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "6kg loose",
    "totalStock": 6,
    "batchNo": "0000039583",
    "mfg": "2026-02-01",
    "exp": "2028-02-01",
    "in": 0,
    "out": 0,
    "opening": 6,
    "location": "F1D18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "TONALIDE",
    "brand": "PFW KEVA",
    "packing": null,
    "article": null,
    "packingDetail": "7.35kg loose",
    "totalStock": 7.35,
    "batchNo": "0000660148",
    "mfg": "2025-10-27",
    "exp": "2027-10-28",
    "in": 0,
    "out": 0,
    "opening": 7.35,
    "location": "F1D18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "TONALIDE",
    "brand": "PFW KEVA",
    "packing": null,
    "article": null,
    "packingDetail": "10.8kg loose",
    "totalStock": 10.8,
    "batchNo": "0000617824",
    "mfg": "2025-05-18",
    "exp": "2027-05-17",
    "in": 0,
    "out": 0,
    "opening": 10.8,
    "location": "F1D18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "TONALIDE",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "0.9kg loose",
    "totalStock": 0.9,
    "batchNo": "20241125",
    "mfg": "2024-11-25",
    "exp": "2026-11-25",
    "in": 0,
    "out": 0,
    "opening": 0.9,
    "location": "F1D18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "TONALIDE",
    "brand": "CHINA",
    "packing": 25,
    "article": null,
    "packingDetail": "1×25kg",
    "totalStock": 25,
    "batchNo": "0000039583",
    "mfg": "2026-02-01",
    "exp": "2028-02-01",
    "in": 0,
    "out": 0,
    "opening": 25,
    "location": "F1D18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "TONALIDE",
    "brand": "PFW KEVA",
    "packing": null,
    "article": null,
    "packingDetail": "1.8kg loose",
    "totalStock": 1.8,
    "batchNo": "0000586297",
    "mfg": "2025-01-22",
    "exp": "2027-01-21",
    "in": 0,
    "out": 0,
    "opening": 1.8,
    "location": "F1D18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "RESINOID LABDANUM RC",
    "brand": "GOLDEN",
    "packing": null,
    "article": null,
    "packingDetail": "1.8kg loose",
    "totalStock": 1.8,
    "batchNo": "P062412",
    "mfg": "2024-06-20",
    "exp": "2026-06-20",
    "in": 0,
    "out": 0,
    "opening": 1.8,
    "location": "F1A17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "RESINOID LABDANUM RC",
    "brand": "GOLDEN",
    "packing": null,
    "article": null,
    "packingDetail": "5kg loose",
    "totalStock": 5,
    "batchNo": "P052618",
    "mfg": "2026-06-21",
    "exp": "2028-06-20",
    "in": 0,
    "out": 0,
    "opening": 5,
    "location": "F1A17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "RESINOID LABDANUM STANDARD",
    "brand": "BMV",
    "packing": null,
    "article": null,
    "packingDetail": "4.8kg loose",
    "totalStock": 4.8,
    "batchNo": "LN060185",
    "mfg": "2026-03-01",
    "exp": "2028-03-01",
    "in": 0,
    "out": 0,
    "opening": 4.8,
    "location": "F1A17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "RESINOID LABDANUM STANDARD",
    "brand": "BMV",
    "packing": 25,
    "article": null,
    "packingDetail": "2×25kg",
    "totalStock": 50,
    "batchNo": "LN060185",
    "mfg": "2026-03-01",
    "exp": "2028-03-01",
    "in": 0,
    "out": 0,
    "opening": 50,
    "location": "F1A17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "RESINOID LABDANUM RC",
    "brand": "BMV",
    "packing": null,
    "article": null,
    "packingDetail": "5kg loose",
    "totalStock": 5,
    "batchNo": "LN060185",
    "mfg": "2026-03-01",
    "exp": "2028-03-01",
    "in": 0,
    "out": 0,
    "opening": 5,
    "location": "F1A17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ISOAMYL PROPIONATE",
    "brand": "UK",
    "packing": null,
    "article": null,
    "packingDetail": "22.2kg loose",
    "totalStock": 22.2,
    "batchNo": "005581",
    "mfg": "2023-01-25",
    "exp": "2025-01-24",
    "in": 0,
    "out": 0,
    "opening": 22.2,
    "location": "F1A17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "INDIAN BASIL OIL",
    "brand": "MOHIT",
    "packing": null,
    "article": null,
    "packingDetail": "23.1kg loose",
    "totalStock": 23.1,
    "batchNo": "LS-BA-43",
    "mfg": "2025-10-01",
    "exp": "2030-09-01",
    "in": 0,
    "out": 0,
    "opening": 23.1,
    "location": "F1A17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "INDIAN BASIL OIL",
    "brand": "MOHIT (COLOR CHANGE)",
    "packing": null,
    "article": null,
    "packingDetail": "1.65kg loose",
    "totalStock": 1.65,
    "batchNo": "LS-BA-11",
    "mfg": "2020-10-01",
    "exp": "2023-09-01",
    "in": 0,
    "out": 0,
    "opening": 1.65,
    "location": "F1A17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BENZYL BENZOATE",
    "brand": "ASHAPURA",
    "packing": null,
    "article": null,
    "packingDetail": "4.8kg loose",
    "totalStock": 4.8,
    "batchNo": "24709",
    "mfg": "2023-12-03",
    "exp": "2025-12-02",
    "in": 0,
    "out": 0,
    "opening": 4.8,
    "location": "F1A17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BENZYL BENZOATE",
    "brand": "LANXESS",
    "packing": null,
    "article": null,
    "packingDetail": "2.28kg loose",
    "totalStock": 2.28,
    "batchNo": "26BB018D",
    "mfg": "2026-03-06",
    "exp": "2027-03-06",
    "in": 0,
    "out": 0,
    "opening": 2.28,
    "location": "F1A17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "BENZYL BENZOATE",
    "brand": "LANXESS",
    "packing": null,
    "article": null,
    "packingDetail": "0.6kg loose",
    "totalStock": 0.6,
    "batchNo": "25BB042D",
    "mfg": "2025-07-16",
    "exp": "2026-07-16",
    "in": 0,
    "out": 0,
    "opening": 0.6,
    "location": "F1A17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ISO AMYL BUTYRATE",
    "brand": "UK",
    "packing": null,
    "article": null,
    "packingDetail": "4.44kg loose",
    "totalStock": 4.44,
    "batchNo": "LN060172",
    "mfg": "2025-11-16",
    "exp": "2026-11-15",
    "in": 0,
    "out": 0,
    "opening": 4.44,
    "location": "F1A17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ISOBUTYL PHENYL ACETATE",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "1.17kg loose",
    "totalStock": 1.17,
    "batchNo": "737701",
    "mfg": "2023-11-23",
    "exp": "2025-11-22",
    "in": 0,
    "out": 0,
    "opening": 1.17,
    "location": "F1A17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GERANYL NITRILE",
    "brand": "JAYSHREE",
    "packing": null,
    "article": null,
    "packingDetail": "2.5kg loose",
    "totalStock": 2.5,
    "batchNo": "2026010901R-082",
    "mfg": "2026-12-09",
    "exp": "2027-12-08",
    "in": 0,
    "out": 0,
    "opening": 2.5,
    "location": "F1A17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GERANYL NITRILE",
    "brand": "JAYSHREE",
    "packing": null,
    "article": null,
    "packingDetail": "2.2kg loose",
    "totalStock": 2.2,
    "batchNo": "2025092301R-222",
    "mfg": "2025-09-23",
    "exp": "2026-09-22",
    "in": 0,
    "out": 0,
    "opening": 2.2,
    "location": "F1A17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GERANYL NITRILE",
    "brand": "ROMA",
    "packing": 25,
    "article": null,
    "packingDetail": "2×25kg",
    "totalStock": 50,
    "batchNo": "MI-GM-260401",
    "mfg": "2026-04-01",
    "exp": "2028-04-01",
    "in": 0,
    "out": 0,
    "opening": 50,
    "location": "F1A17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GERANYL NITRILE",
    "brand": "ROMA",
    "packing": null,
    "article": null,
    "packingDetail": "12.57kg loose",
    "totalStock": 12.57,
    "batchNo": "MI-GM-260401",
    "mfg": "2026-04-01",
    "exp": "2028-04-01",
    "in": 0,
    "out": 0,
    "opening": 12.57,
    "location": "F1A17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PARA CRESYL ACETATE",
    "brand": "UK",
    "packing": null,
    "article": null,
    "packingDetail": "1.65kg loose",
    "totalStock": 1.65,
    "batchNo": "007480",
    "mfg": "2023-09-18",
    "exp": "2025-09-17",
    "in": 0,
    "out": 0,
    "opening": 1.65,
    "location": "F1A17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PARA CRESYL ACETATE",
    "brand": "UK",
    "packing": null,
    "article": null,
    "packingDetail": "0.76kg loose",
    "totalStock": 0.76,
    "batchNo": "701523",
    "mfg": "2022-11-04",
    "exp": "2024-11-04",
    "in": 0,
    "out": 0,
    "opening": 0.76,
    "location": "F1A17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "METHYL PHENYL ACETATE",
    "brand": "UK",
    "packing": null,
    "article": null,
    "packingDetail": "0.6kg loose",
    "totalStock": 0.6,
    "batchNo": "007121",
    "mfg": "2022-10-14",
    "exp": "2024-10-13",
    "in": 0,
    "out": 0,
    "opening": 0.6,
    "location": "F1A17",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AQUALIM",
    "brand": "AQUILA",
    "packing": null,
    "article": null,
    "packingDetail": "25×4kg loose",
    "totalStock": 100,
    "batchNo": "084/010/10/25",
    "mfg": "2025-10-30",
    "exp": "2027-10-29",
    "in": 0,
    "out": 0,
    "opening": 100,
    "location": "F1A18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AQUALIM",
    "brand": "AQUILA",
    "packing": null,
    "article": null,
    "packingDetail": "0.6kg loose",
    "totalStock": 0.6,
    "batchNo": "084/010/10/25",
    "mfg": "2025-10-30",
    "exp": "2027-10-29",
    "in": 0,
    "out": 0,
    "opening": 0.6,
    "location": "F1A18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NIMBEROL",
    "brand": "HEMANI",
    "packing": null,
    "article": null,
    "packingDetail": "4kg loose",
    "totalStock": 4,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 4,
    "location": "F1A18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "NIMBEROL",
    "brand": "HEMANI",
    "packing": null,
    "article": null,
    "packingDetail": "1kg loose",
    "totalStock": 1,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 1,
    "location": "F1A18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "L-ISO PULEGOL FG",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "28.45kg loose",
    "totalStock": 28.45,
    "batchNo": "6543279T0",
    "mfg": "2026-10-27",
    "exp": "2027-11-26",
    "in": 0,
    "out": 0,
    "opening": 28.45,
    "location": "F1A18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "L-ISO PULEGOL FG",
    "brand": "BASF",
    "packing": 30,
    "article": null,
    "packingDetail": "2×30kg",
    "totalStock": 60,
    "batchNo": "35358588Q0",
    "mfg": "2024-08-01",
    "exp": "2026-08-01",
    "in": 0,
    "out": 0,
    "opening": 60,
    "location": "F1A18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "L-ISO PULEGOL FG",
    "brand": "BASF",
    "packing": null,
    "article": null,
    "packingDetail": "19.6kg loose",
    "totalStock": 19.6,
    "batchNo": "35358588Q0",
    "mfg": "2024-08-01",
    "exp": "2026-08-01",
    "in": 0,
    "out": 0,
    "opening": 19.6,
    "location": "F1A18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CYCLOGAL BANATE",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "1kg loose",
    "totalStock": 1,
    "batchNo": "20250902",
    "mfg": "2025-09-02",
    "exp": "2026-09-01",
    "in": 0,
    "out": 0,
    "opening": 1,
    "location": "F1A18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CYCLOGAL BANATE",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "2.5kg loose",
    "totalStock": 2.5,
    "batchNo": "LN060207",
    "mfg": "2026-05-02",
    "exp": "2027-05-01",
    "in": 0,
    "out": 0,
    "opening": 2.5,
    "location": "F1A18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "GALBADOR CG",
    "brand": "ORGANIC AROMATICS",
    "packing": null,
    "article": null,
    "packingDetail": "0.36kg loose",
    "totalStock": 0.36,
    "batchNo": "20D15003-04",
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 0.36,
    "location": "F1A18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "LYRAL",
    "brand": "CHINA",
    "packing": 30,
    "article": null,
    "packingDetail": "3×30kg",
    "totalStock": 90,
    "batchNo": "37623",
    "mfg": "2025-11-08",
    "exp": "2026-11-07",
    "in": 0,
    "out": 0,
    "opening": 90,
    "location": "F1A18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "LYRAL",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "29.74kg loose",
    "totalStock": 29.74,
    "batchNo": "37623",
    "mfg": "2025-11-08",
    "exp": "2026-11-07",
    "in": 0,
    "out": 0,
    "opening": 29.74,
    "location": "F1A18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "LYRAL",
    "brand": "CHINA",
    "packing": null,
    "article": null,
    "packingDetail": "2.3kg loose",
    "totalStock": 2.3,
    "batchNo": "LN060233",
    "mfg": "2026-06-08",
    "exp": "2027-06-07",
    "in": 0,
    "out": 0,
    "opening": 2.3,
    "location": "F1A18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "CYCLOGALBANATE",
    "brand": null,
    "packing": null,
    "article": null,
    "packingDetail": "1.5kg loose",
    "totalStock": 1.5,
    "batchNo": "LN060207",
    "mfg": "2026-05-02",
    "exp": "2027-05-01",
    "in": 0,
    "out": 0,
    "opening": 1.5,
    "location": "F1A18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PHENYL ETHYL ISO BUTYRATE",
    "brand": "JAYSHREE",
    "packing": null,
    "article": null,
    "packingDetail": "4.9kg loose",
    "totalStock": 4.9,
    "batchNo": "2025090601R-159",
    "mfg": "2025-09-06",
    "exp": "2026-09-05",
    "in": 0,
    "out": 0,
    "opening": 4.9,
    "location": "F1A18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PHENYL ETHYL ISO BUTYRATE (PEB)",
    "brand": "HARMONY",
    "packing": 35,
    "article": null,
    "packingDetail": "3×35kg",
    "totalStock": 105,
    "batchNo": "PEB26010008",
    "mfg": "2026-01-06",
    "exp": "2027-01-05",
    "in": 0,
    "out": 0,
    "opening": 105,
    "location": "F1A18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "PHENYL ETHYL ISO BUTYRATE (PEB)",
    "brand": "HARMONY",
    "packing": null,
    "article": null,
    "packingDetail": "29.95kg loose",
    "totalStock": 29.95,
    "batchNo": "PEB26010008",
    "mfg": "2026-01-06",
    "exp": "2027-01-05",
    "in": 0,
    "out": 0,
    "opening": 29.95,
    "location": "F1A18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "RESINOID BALSUM TOLU SPECIAL",
    "brand": "GOLDEN",
    "packing": 25,
    "article": null,
    "packingDetail": "6×25kg",
    "totalStock": 150,
    "batchNo": null,
    "mfg": null,
    "exp": null,
    "in": 0,
    "out": 0,
    "opening": 150,
    "location": "F1A18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ISO AMYL BUTYRATE",
    "brand": "S.G.",
    "packing": 30,
    "article": null,
    "packingDetail": "2×30kg",
    "totalStock": 60,
    "batchNo": "IABU/080004/26-27",
    "mfg": "2026-05-01",
    "exp": "2028-05-01",
    "in": 0,
    "out": 0,
    "opening": 60,
    "location": "F1A18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "ISO AMYL BUTYRATE",
    "brand": "S.G.",
    "packing": null,
    "article": null,
    "packingDetail": "24.95kg loose",
    "totalStock": 24.95,
    "batchNo": "IABU/080004/26-27",
    "mfg": "2026-05-01",
    "exp": "2028-05-01",
    "in": 0,
    "out": 0,
    "opening": 24.95,
    "location": "F1A18",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AQUALIM",
    "brand": "AQUILA",
    "packing": 5,
    "article": null,
    "packingDetail": "15×5kg",
    "totalStock": 75,
    "batchNo": "084/011/11/25",
    "mfg": "2025-11-08",
    "exp": "2027-11-07",
    "in": 0,
    "out": 0,
    "opening": 75,
    "location": "F1A19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AQUALIM",
    "brand": "AQUILA",
    "packing": null,
    "article": null,
    "packingDetail": "3.92kg loose",
    "totalStock": 3.92,
    "batchNo": "084/016/12/25",
    "mfg": "2025-12-27",
    "exp": "2027-12-26",
    "in": 0,
    "out": 0,
    "opening": 3.92,
    "location": "F1A19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AQUALIM",
    "brand": "AQUILA",
    "packing": null,
    "article": null,
    "packingDetail": "1kg loose",
    "totalStock": 1,
    "batchNo": "084/016/12/25",
    "mfg": "2025-12-27",
    "exp": "2027-12-26",
    "in": 0,
    "out": 0,
    "opening": 1,
    "location": "F1A19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AQUALIM",
    "brand": "AQUILA",
    "packing": 5,
    "article": null,
    "packingDetail": "15×5kg",
    "totalStock": 75,
    "batchNo": "084/002/04/26",
    "mfg": "2026-04-30",
    "exp": "2028-04-29",
    "in": 0,
    "out": 0,
    "opening": 75,
    "location": "F1A19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AQUALIM",
    "brand": "AQUILA",
    "packing": 5,
    "article": null,
    "packingDetail": "5×5kg",
    "totalStock": 25,
    "batchNo": "084/022/03/26",
    "mfg": "2026-03-23",
    "exp": "2028-03-22",
    "in": 0,
    "out": 0,
    "opening": 25,
    "location": "F1A19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AQUALIM / NORLIBONAL",
    "brand": "AQUILA",
    "packing": null,
    "article": null,
    "packingDetail": "0.48kg loose",
    "totalStock": 0.48,
    "batchNo": "084/009/01/24",
    "mfg": "2024-01-01",
    "exp": "2026-01-01",
    "in": 0,
    "out": 0,
    "opening": 0.48,
    "location": "F1A19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AMBERTAL K",
    "brand": "ORIENTAL",
    "packing": 5,
    "article": null,
    "packingDetail": "11×5kg",
    "totalStock": 55,
    "batchNo": "V26F006553",
    "mfg": "2026-02-13",
    "exp": "2027-02-12",
    "in": 0,
    "out": 0,
    "opening": 55,
    "location": "F1A19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AMBERTAL K",
    "brand": "ORIENTAL",
    "packing": 5,
    "article": null,
    "packingDetail": "8×5kg",
    "totalStock": 40,
    "batchNo": "V26F006483",
    "mfg": "2026-01-29",
    "exp": "2027-01-28",
    "in": 0,
    "out": 0,
    "opening": 40,
    "location": "F1A19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AMBERTAL K",
    "brand": "ORIENTAL",
    "packing": null,
    "article": null,
    "packingDetail": "3.995kg loose",
    "totalStock": 3.995,
    "batchNo": "V26F006483",
    "mfg": "2026-01-29",
    "exp": "2027-01-28",
    "in": 0,
    "out": 0,
    "opening": 3.995,
    "location": "F1A19",
    "reservation": null
  },
  {
    "tally": null,
    "material": "AMBERTAL K",
    "brand": "ORIENTAL",
    "packing": null,
    "article": null,
    "packingDetail": "0.3kg loose",
    "totalStock": 0.3,
    "batchNo": "V23F001018",
    "mfg": "2023-05-04",
    "exp": "2024-05-04",
    "in": 0,
    "out": 0,
    "opening": 0.3,
    "location": "F1A19",
    "reservation": null
  }
];

export const NEW_LOCATIONS = [
  "F1A17",
  "F1A18",
  "F1A19",
  "F1B5",
  "F1D13",
  "F1D14",
  "F1D15",
  "F1D17",
  "F1D18"
];
